### ISSUE TITLE
Raiden CLTV increase max

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1053]
raiden cltv's : if first leg is raiden, second bitcoin, then raiden lock duration is 100 eth blocks and no api to control it. current default 50 off-chain + another 50 on-chain. Maximum practical maximum is 500 blocks off-chain + 500 block on-chain. 250 minutes. Which is practically too short to include lightning as second leg.

we agreed on starting with patching raiden default and max first, ideally make it configurable. Needs checking some lnbtc routes what are long cltv values out there and then set the maximum of raiden to something high enough that it can include it in any case with a decent buffer. That's our own raiden fork and we assume people will use this in our setup. We keep the option to "force raiden on the second leg" for the future in case these changes don't get merged

**Comment by kilrau** [comment]
To be researched: why is it that one has to wait 10x the locktime to close a channel on raiden. With max values of around 10k blocks (to be confirmed!) on raiden (~1.7 days), x10 would be 100k block (~17 days). That's a bit too long to wait to get funds back.

**Comment by kilrau** [comment]
Goal for the call: final decision if we do this OR go for the requestor/initiator model to force raiden on the second leg. @offerm

**Comment by kilrau** [comment]
Trade-off:
1. reveal time 1 week: settle time 2 weeks (why?)
2. node can't open another channel to the peer in the same time.

**Comment by offerm** [comment]
So, we implemented this:

settle_timeout - big number - 20660 to allow 10 hops second leg.
reveal_timeout - 50 blocks (as default)
Lock_timeout - new API parameters. Value between 151 and 20260.

Done

**Comment by kilrau** [comment]
Could you quickly explain why "Value between 151 and 20260"?

**Comment by michael1011** [comment]
@kilrau I guess that 151 is hardcoded in Raiden as the lowest number of blocks for locks and 20660 because that is the maximal `setttle_timeout`defined in the contract and the `lock_timeout` has to be less or equal to `settle_timeout`.

**Comment by kilrau** [comment]
Makes sense, 20*2*60 is a typo then. Thx!

**Comment by offerm** [comment]
Default raiden for a single payment is: reveal timeout= 50, lock_timeout = 100, settle_timeout=500.

We assume a second leg of 1 to 10 BTC hops.

One hope = 144 CLTV blocks -> 1440 minutes -> 5760 eth blocks
10 hopes = 144+9*40 blocks = 504 blocks -> 5040 minutes -> 20160 eth blocks

So settle_timeout = 20160+500 -> 20660.
reveal_timeout = 50 (50 blocks before lock expiration) raiden will register the secret on chain.
lock_timeout = any value between 5760+100 and 20160+100.

Since second leg can also be raiden, lock_timeout can also be 100+100.

So lock_timeout - value between 200 to 20260.

Nice try @michael1011

**Comment by michael1011** [comment]
An attempt was made...

In the comment before you said:
```
 Lock_timeout - new API parameters. Value between 151 and 20260.
```

It the lowest lock timeout 151 or 200 blocks now?

**Comment by offerm** [comment]
From raiden point of view - lock_timeout can be any value between reveal_timeout and settle_timeout.

From xud point of view - lock_timeout should be 100+second leg. (we need to implement a check for it.)

**Comment by sangaman** [comment]
> So, we implemented this:
> 
> settle_timeout - big number - 20660 to allow 10 hops second leg.
> reveal_timeout - 50 blocks (as default)
> Lock_timeout - new API parameters. Value between 151 and 20260.

Is there code or documentation/discussion you can point me to to learn more about `lock_timeout`? I couldn't find anything recent in the raiden repo.

> From xud point of view - lock_timeout should be 100+second leg. (we need to implement a check for it.)

It could be more though, right? 100 seems low to me, it's only 2.5 bitcoin blocks or 25 minutes.

One scenario I am thinking of is where we have 100 bitcoin blocks total delay for the 2nd leg, which equals 4000 raiden blocks or 1000 minutes on average. If we do 100 + 4000 = 4100 for the 1st leg on raiden, we'd get 1025 minutes on average. Since block times vary and the ETH and BTC chains are independent of each other, it's fairly likely that there are 4100 new ETH blocks before 100 new BTC blocks, which means that the 1st leg would expire before the 2nd leg and the taker could technically steal funds from the maker. Having a significant "buffer" on the hop from one chain to another seems important.
