### ISSUE TITLE
unit renaming

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1104]
Status Quo:
`units`: 18 decimals for weth and dai, 8 decimals for ltc & btc, more differing to come
`amounts`: 8 decimals normalized for all

which I find rather confusing.

Proposal:
`native_units`: 18 decimals for weth and dai, 8 decimals for ltc & btc, more differing to come
`normalized_units`: 8 decimals normalized for all

Open for other proposals!

**Comment by sangaman** [comment]
The status quo is actually not that consistent, as "amount" is sometimes used interchangeably.

Since these variable names are strictly used internally, I don't think they need to be particularly descriptive as long as they are commented properly and used consistently. The goal is to prevent unintentional bugs due to confusion. I opened a PR that attempts to do that, but keeps the naming as `amount` and `units`.

I am thinking maybe we could switch all `amount` references to `quantity` since they are both always 10^-8, which would bring the swaps naming style (amount) in line with the orderbook naming style (quantity), possibly preventing some confusion. "Units" is only used in the context of swaps/swap clients. Thoughts @erkarl?

**Comment by erkarl** [comment]
I'm good with both options. My main concern is getting in consistent in the codebase to prevent bugs.

**Comment by sangaman** [comment]
OK, I think for now I'd probably be fine with my PR as is since it fixes the inconsistent usage of `amount`, and keep the thought of using `quantity` instead of `amount` in my head in case it makes sense down the road.

**Comment by kilrau** [comment]
Alright.
