### ISSUE TITLE
Initialize lnd/raiden after xud is unlocked

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1196]
As @erkarl mentioned in this [comment](https://github.com/ExchangeUnion/xud/pull/1192#pullrequestreview-282136339), `xud` should be able to reconnect to a L2 client (e.g. raiden could crash and be restarted by our docker setup) after xud has already been unlocked.

**Comment by sangaman** [comment]
@erkal This should already happen, when we mark a client as `Disconnected` we begin a timer to periodically recheck to see if the client is back online. I do notice now though that we don't detect automatically when lnd shuts down - which is odd because that definitely used to work. The `error` event on lnd server streaming calls doesn't seem to be firing. I'll investigate that, but once that's figured I figure we can close this issue if I understand it correctly.

**Comment by erkarl** [comment]
> Oh I misunderstood then, are you suggesting keeping the password in memory such that if lnd goes into the `WaitingUnlock` state, xud unlocks it automatically? If so I can go ahead and open a PR to add that functionality.

Yes, looks like this is solved by:
https://github.com/ExchangeUnion/xud/pull/1224
&
https://github.com/ExchangeUnion/xud/pull/1226
