### ISSUE TITLE
Initialize ETH keystore file/wallet from master seed

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1242]
Currently the master seed does NOT restore the geth seed

Idea to include seedutil (go): when installing from npm: `npm install -g xud` - bundle 2 executables together

Also: this includes a PR against xud-docker to include the same functionality there

**Comment by sangaman** [comment]
The tricky part about bundling the seedutil executable via npm is that we'll need to target the user's platform & architecture, otherwise it won't work. I did some research on possible solutions and this seemed to be the most promising: https://www.npmjs.com/package/go-npm. I'll look into it more closely after I open the PR for this issue.
