### ISSUE TITLE
xud starting...

### ISSUE THREAD

**Issue by peartobear** [ExchangeUnion/xud#1258]
Currently, the error message isn't legible and doesn't indicate if `xud` is ready for the gRPC calls. Refactor it to include the status of `xud` like: "xud is starting... Try again in a few seconds" to make it more apparent.

**Comment by sangaman** [comment]
#1248 might resolve this by waiting a short time on the `create` and `unlock` calls, however it's not waiting on other calls. My thinking there is there will need to be a `create` or `unlock` at the beginning.

We can't tell if xud is starting or not - only if it's up or not. As for the message, we can change it to make it say something more descriptive instead of the generic grpc `UNAVAILABLE` message. Maybe something like "could not connect to xud on [host/port], check to make sure it is running"?

**Comment by kilrau** [comment]
> #1248 might resolve this by waiting a short time on the create and unlock calls, however it's not waiting on other calls.

Unfortunately not helping much here. Especially because I think we should target to have the `getinfo` call working even when `xud` is locked. Just like `lnd`.

> We can't tell if xud is starting or not - only if it's up or not.

But we have to eventually. No need to know which phase of "starting" we are in, but we have to be able to distinguish between "xud is starting" and "xud is not available". Let's discuss how @sangaman @erkarl @michael1011 

After this, we can improve the error message for these two cases
* "xud is starting... Try again in a few seconds."
* "Could not connect to xud on [host/port]. Make sure it is running."

**Comment by michael1011** [comment]
We could check the log file to find out whether xud is running (by the timestamp and the last line in the log) and at what stage in the startup process it is right now.

`bitcoin-cli` shows messages (like `Rewinding blocks...`) before the RPC interface started. We could also check how Bitcoin Core has managed to do that.

**Comment by sangaman** [comment]
> Unfortunately not helping much here. Especially because I think we should target to have the getinfo call working even when xud is locked. Just like lnd.

Lnd doesn't support the getinfo call while it's locked, you get this error message: "[lncli] Wallet is encrypted. Please unlock using 'lncli unlock', or set password using 'lncli create' if this is the first time starting lnd." We can have a similar message though instead of the `UNIMPLEMENTED` error. We can't really have an actual getinfo response because most of the data isn't available yet at that point.

> But we have to eventually. No need to know which phase of "starting" we are in, but we have to be able to distinguish between "xud is starting" and "xud is not available". Let's discuss how @sangaman @erkarl @michael1011
> 
> After this, we can improve the error message for these two cases
> 
>     "xud is starting... Try again in a few seconds."
>     "Could not connect to xud on [host/port]. Make sure it is running."

I'm still not sure this is worth the trouble, there isn't much of a "startup" period for xud. It doesn't verify blocks or anything like that. It opens the database and reads the nodekey, both of which are very fast operations. It currently may wait up to 5 seconds for lnd & raiden to be available, but we can easily remove that wait.

The alternative is to immediately start a grpc server that returns the `UNAVAILABLE` error to every call with a message saying that xud is starting. But I think practically speaking in most cases it would only be up for a matter of milliseconds and it conveys the same idea to the client- that xud is not currently ready for calls.

> We could check the log file to find out whether xud is running (by the timestamp and the last line in the log) and at what stage in the startup process it is right now.

The log file would be kind of tricky (we'd have to make sure we're reading the right file and parsing properly) and imperfect (xud could have logged some output recently and then stopped), so I'd rather start the grpc server first thing

> bitcoin-cli shows messages (like Rewinding blocks...) before the RPC interface started. We could also check how Bitcoin Core has managed to do that.

The RPC server has started in those cases, it's just returning that fixed response for all calls. But I think it makes sense in that case because it can take minutes between the time bitcoin has started and when it is ready to handle normal calls.

**Comment by sangaman** [comment]
In thinking about this a bit more, I'm warmer to the idea of starting an rpc server immediately that just returns the `UNAVAILABLE` error with a message saying that xud is starting that I mentioned above. Then tools like the cli could detect this and say that xud is starting.
