### ISSUE TITLE
Replace Order

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1313]
Traditional exchanges provide "cancel-replace" order or "order-cancel-order" (OCO) functionality, we should provide something similar. Reasons:
* market makers continuously need to replace orders since the price on the exchanges they are connected to is continuously moving. As of now this requires two API calls:  https://api.exchangeunion.com/#removeorder & https://api.exchangeunion.com/#placeorder. This is not what market makers are used to.
* Also, as of now, two packets need to be broadcasted to the network: invalidating the old order and broadcasting the new order. Since time is of the essence and prices can move fast, we'd want to reduce this to one `replace_order` packet only.

Obviously, we need to take great care for the sender to sign and recipient to verify signature, so that a node can only replace its own orders (compare https://github.com/ExchangeUnion/xud/issues/242).

**Comment by kilrau** [comment]
Implementation-wise, @reliveyy recommends to **not** change order price or quantity, but to actually replace it with a new order (and new order id). Simpliefies xud's matching engine since it can assume an order doesn't change.

**Comment by LePremierHomme** [comment]
> Obviously, we need to take great care for the sender to sign and recipient to verify signature, so that a node can only replace its own orders (compare #242).

As discussed in #242, signing isn't required here, since authentication is done during the handshake, and communication is limited to the secured socket. Correct?

> Implementation-wise, @reliveyy recommends to not change order price or quantity, but to actually replace it with a new order (and new order id). Simpliefies xud's matching engine since it can assume an order doesn't change.

Sounds like a good suggestion. So `replace_order` would be similar to `order`, only that it will carry an additional field for the order to cancel?

**Comment by kilrau** [comment]
> As discussed in #242, signing isn't required here, since authentication is done during the handshake, and communication is limited to the secured socket. Correct?

As of now correct. With upcoming p2p protocol changes this will be required since this packet will not be limited to the secure socket anymore. But I guess it makes sense to wait until we get there. So I agree, not need in the course of this PR.

> Sounds like a good suggestion. So replace_order would be similar to order, only that it will carry an additional field for the order to cancel?

an additional field for another order to cancel yeah. That what you had in mind? @reliveyy Other opinions? @sangaman @erkarl @offerm

**Comment by LePremierHomme** [comment]
It looks like that creating a new API call `ReplaceOrder` which will combine both `RemoveOrder` and `PlaceOrder` is somehow straightforward, but making them atomic in the P2P level isn’t.

Steps:
1. attempt to remove the old order. If some of its quantity is “on-hold” (during a swap), return an error. Otherwise it’s not clear whether it will _eventually_ be removed or not, or whether we wish to replace just the "removable" portion or not (this would require a clumsy API). 
2. if order was removed locally, `orderInvalidation` packet shouldn’t be sent (this might create some race-conditions).
3. if the new order was matched locally fully, send `orderInvalidation` packet for the old order. if it wasn’t matched fully, send `replaceOrder` packet with the non-matched portion of the new order, and the old order id to invalidate. 

This will also require changes in the API events. We currently have `peerOrder.incoming`, `peerOrder.invalidation`, `ownOrder.added`, `ownOrder.removed`. to support atomic operation, we will need to add `peerOrder.replaced`, `ownOrder.replaced`.

So it looks like step **1** would be required anyway, but **2** and **3** can be avoided, since they will require some non-trivial code changes, while they are not completely necessary. Instead, `orderInvalidation` and `order` packets will be sent sequentially, as usual (if we’ll move to gossip communication at some point, we can add messages ordering from the sender perspective, to take care of that).

Please advise @sangaman @kilrau @michael1011 @erkarl @reliveyy

**Comment by kilrau** [comment]
After thinking about this some more, I think it's enough to simply have a `replaceorder` call on the xud gRPC level and to not change anything on the p2p layer since that looks fairly complicated.

Regarding your question that means, we can skip 2. and 3. and for 1. I'd suggest to not replace anything if part or the whole order is on-hold. I'd keep re-trying to replace the order until the on-hold order is either filled and can't be replaced (throw error) or swap in-progress fails, hold is removed and can be replaced (success).

**Comment by LePremierHomme** [comment]
* `PlaceOrder` is exposed in the CLI as `buy`/`sell` commands
* `PlaceOrder` have sync and non-sync versions

Implementing all of these for `ReplaceOrder` would be an overkill, while not doing so might create a API usage difficulty. So i’m thinking to follow @sangaman advice, and implement `ReplaceOrder` as an additional optional field to `PlaceOrder`. 
@kilrau do you agree?

**Comment by kilrau** [comment]
@kilrau do you agree?

Yes!
