### ISSUE TITLE
Reputation System Fixes

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1422]
- what events do we have
- scores each
- where stored

EDIT: What we currently have is
```
  [ReputationEvent.ManualBan]: Number.NEGATIVE_INFINITY,
  [ReputationEvent.ManualUnban]: 0,
  [ReputationEvent.PacketTimeout]: -1,
  [ReputationEvent.SwapFailure]: -10,
  [ReputationEvent.SwapSuccess]: 1,
  [ReputationEvent.WireProtocolErr]: -5,
  [ReputationEvent.InvalidAuth]: -20,
  [ReputationEvent.SwapTimeout]: -15,
  [ReputationEvent.SwapMisbehavior]: -20,
```

and ` private static readonly BAN_THRESHOLD = -50;` stored with each node in the db.

In-code todo's:
```
// TODO: inform node about getting banned
// TODO: remove reputation events after certain amount of time
```

Agree on the first, not sure about the second. Thoughts? @sangaman 

New Todo's:
-  negative infinity / setting to 0 for manual ban/unban is problematic IMO because a given node would "loose" it's reputation history. E.g. a node with a high positive score that I accidentally ban and immediately unban would be reset to 0. The same would happen with a node I actually banned with a bad reputation score.
- We should have upper/lower bounds for the scores. Reason: a node going offline over night might cause tons of negative reputation events e.g. going to -5000 getting it disconnected from all it's peers without the chance to ever collect positive score reputation events again. Same for positive: Once a node collected a very high positive reputation score, it can repeatedly misbehave for financial gain for quite some time before reaching -50.

**Comment by kilrau** [comment]
Related: Bitcoin core `banscore` events mostly maxscore leading to immediate ban: https://bitcoin.stackexchange.com/questions/93795/why-does-the-banscore-default-to-100

**Comment by kilrau** [comment]
This one should be a low-hanging fruit @sangaman

**Comment by sangaman** [comment]
> In-code todo's:
> 
> ```
> // TODO: inform node about getting banned
> // TODO: remove reputation events after certain amount of time
> ```
> 
> Agree on the first, not sure about the second. Thoughts? @sangaman

The first one is tracked by #958, but that PR needs some work. Last I remember working on it there were issues with the tests that I could not resolve.

The second one I have mixed opinions on. I'd be ok with leaving it as open question, for now I wouldn't bother it.
 
> New Todo's:
> 
>     * negative infinity / setting to 0 for manual ban/unban is problematic IMO because a given node would "loose" it's reputation history. E.g. a node with a high positive score that I accidentally ban and immediately unban would be reset to 0. The same would happen with a node I actually banned with a bad reputation score.

I'm not sure how common accidental banning would be, but I can see about merely canceling out a manual ban event given an unban event so that the pre-existing score carries over. In case of a non-manual ban, it makes sense to start off at 0 right?

>     * We should have upper/lower bounds for the scores. Reason: a node going offline over night might cause tons of negative reputation events e.g. going to -5000 getting it disconnected from all it's peers without the chance to ever collect positive score reputation events again. Same for positive: Once a node collected a very high positive reputation score, it can repeatedly misbehave for financial gain for quite some time before reaching -50.

I agree for the upper bound, and that should be easy enough to do. For the lower bound, once you reach the ban threshold you should be banned and therefore not have the ability to rack up an even lower score (nor will you have a chance to rehabilitate your score). You'd have to get manually unbanned at that point, which would start you off at 0 again regardless of what your score was.

**Comment by kilrau** [comment]
> The first one is tracked by #958, but that PR needs some work. Last I remember working on it there were issues with the tests that I could not resolve.

> The second one I have mixed opinions on. I'd be ok with leaving it as open question, for now I wouldn't bother it.

Agreed, we are good here for now.

> In case of a non-manual ban, it makes sense to start off at 0 right?

Yes.

> I agree for the upper bound, and that should be easy enough to do. For the lower bound, once you reach the ban threshold you should be banned and therefore not have the ability to rack up an even lower score (nor will you have a chance to rehabilitate your score).

Which is essentially behaving like a lower bound. Sounds good.

> You'd have to get manually unbanned at that point, which would start you off at 0 again regardless of what your score was.

Ok.


Good to go?

**Comment by sangaman** [comment]
> Related: Bitcoin core `banscore` events mostly maxscore leading to immediate ban: https://bitcoin.stackexchange.com/questions/93795/why-does-the-banscore-default-to-100

Thinking about this, I think we can consider making the errors more serious that are likely caused by version/protocol incompatibility or especially caused by deliberate misbehavior or code modification. In those cases we should have little to no tolerance before banning. Where some buffer makes sense is on swap failures, those will happen from time to time due to routes changing, hop nodes going offline, etc... But we really don't want them to happen too often, especially if there aren't a lot of successful swaps happening in between.

For now I'll go ahead with the maximum score as a good intermediary step but the above might make sense for next steps.
