### ISSUE TITLE
Mainnet | Getnodeinfo throwing an error - node <node_id> is unknown

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud#1427]
**Describe the bug**
On mainnet, Getnodeinfo command returns error - node <node_id> is unknown

**To Reproduce**
1. Connect to AWS EC2 instance
2. Run the installation
3. Select mainnet
4. Once the installation is done, run getinfo
5. From the getinfo details, select node id
6. Run getnodeinfo <node_id> from step 5
7. Validate result

**Expected behavior**
At step 7 - it should show node info 

**Actual behaviour**
At step 7 - it shows node <node_id> is unknown

**Screenshots**
![Screenshot 2020-03-04 at 2 02 24 PM](https://user-images.githubusercontent.com/18718151/75860099-47d08100-5e21-11ea-9f5d-7cdfed9d2592.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sangaman** [comment]
Sorry it took me a while to take a look at this issue. The steps make it sound like you are doing `getnodeinfo` on yourself. If so, I would expect to receive the `NOT_FOUND` error since it isn't supposed to be used on yourself, but maybe we could change that error.

However, you shouldn't need to be actively connected to the node to get info about them. In my limited experience using this call it has worked for me even with nodes I'm not connected to. I'll be using this call more going forward so I'll pay attention if I run into this, otherwise if there are steps to reproduce with a node that definitely isn't ourselves and definitely is a node that has existed, then I'll try to reproduce.
