### ISSUE TITLE
Simulation Tests: Connext 

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1460]
Let's flesh out some details @LePremierHomme , but in general it should be similar to the previous raiden test suite, but using ganache instead of geth. Can't find the commit where you deleted all raiden tests, but I bet you can @LePremierHomme . Let's start from there.

**Comment by michael1011** [comment]
I think we should use [ganache](https://github.com/trufflesuite/ganache-cli) for connext tests unless we want to include raiden in the simulation tests again. Easier to setup and maintain.

**Comment by LePremierHomme** [comment]
The removal of `geth`/`raiden` was part of dockerizing the sim tests, since they caused many issues. Here's the commit: https://github.com/ExchangeUnion/xud/pull/1357/commits/7ad9693384979fc8140c324b399154a99791a3dc
It removed 3 things:
1. `geth` setup 
2. `raiden` setup
3. test code

If using `ganache`+`connext`, it's most likely that only the test code will be reusable.

Where can I find a guide for deploying `connext` on a local/private network?

**Comment by kilrau** [comment]
> If using `ganache`+`connext`, it's most likely that only the test code will be reusable.

Sounds about right.


> Where can I find a guide for deploying `connext` on a local/private network?

https://github.com/ConnextProject/indra#launch-indra-in-developer-mode

**Comment by LePremierHomme** [comment]
What's `xud` latest status regarding supporting `connext` as swap client?

**Comment by kilrau** [comment]
Close :) https://github.com/ExchangeUnion/xud/pull/1424

**Comment by LePremierHomme** [comment]
When it is expected to get merged?

**Comment by kilrau** [comment]
Within the next 2–3 weeks I would say. But @erkarl can give a more detailed estimation.

Anyhow, thats why this issue is assigned to the next milestone `beta.4`.

**Comment by LePremierHomme** [comment]
Ok, so looks like the missing details are rather technical, and i'll be able to know/specify them only once i'll start working on this.

**Comment by LePremierHomme** [comment]
Closed by https://github.com/ExchangeUnion/xud/pull/1657.
