### ISSUE TITLE
Peer penalization history

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#151]
Maintain the penalization history for each peer, while specifying the reason for each penalty (enum), instead of merely updating the ban score (the current behavior). 
The score itself could be maintained separately (as it's being done now), or be calculated from the history. This history should be sent to the peer when the ban threshold exceeds, before disconnecting from him, as a payload to the `disconnecting` packet.

Need to think whether we want to dump this history to the database before destroying the peer object, which will contain it.

**Comment by kilrau** [comment]
In short: local blacklists which are exchanged via P2P layer

**Comment by sangaman** [comment]
I think the focus for this issue is just keeping the history for local purposes as well as informing the banned peer, not for sharing blacklists with other peers. That might be something we'd want to allow for, but it can't be done automatically since banlists are easily faked and there's no network consensus mechanism to determine which peers are misbehaving. My thinking originally is that you can manually blacklist peers, and that users might choose to blacklist peers based on the blacklists of particular peers that they trust, but we wouldn't need to do anything for that besides a way to manually ban peers.
