### ISSUE TITLE
bug: ENDENT error if user requests getinfo during initialization of xud

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1510]
### Background

TS error appeared if user requests getinfo during initialization of xud.
![Screen](https://user-images.githubusercontent.com/29906866/80481910-001b3100-895c-11ea-8cca-48ac6e308c17.png)

### Steps to reproduce

1. bash xud.sh 
2. wait for container creation
3. use getinfo after xud container creation

### Expected behaviour

Readable error without error trace (see status output)

**Comment by kilrau** [comment]
The only way I can imagine to prevent this (without getting complicated) is `xucli` responding with the same `Can't connect to xud on port X, is it running?` even though tls.cert doesn't exist yet. Since this can only happen in a split second edge case we want a quick and easy solution here. Other ideas? @sangaman

**Comment by rsercano** [comment]
I can simply check if tls.cert is created yet, and as you mentioned simply say xud is not running yet if you wish @kilrau ?
