### ISSUE TITLE
cli: Error with traceroute misuse addcurrency command

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1539]
### Description

When string used as [decimal_places] parameter in addcurrency parameter, cli output returns Assertion Error

### Steps to reproduce

1. addcurrency ADH Connext  0xe69a353b3152dd7b706ff7dd40fe1d18b7802d31

### Expected behaviour

only help printed

### Actual behaviour

help + error with traceroute are printed
![Screenshot](https://user-images.githubusercontent.com/29906866/81329686-927fab00-90a7-11ea-8daf-72f92f19caeb.png)

**Comment by sangaman** [comment]
It's the behavior of yargs (the command line library we're using) to print the error trace when a command throws an exception, so we'd probably see similar output in other commands where invalid arguments are used. I'm not sure if there's a clean/simple way to handle this sort of thing across the board. I don't think it's too much of a problem as is, particularly since it won't come up often and just means a some unnecessary output, but I'll put in a quick fix to print a nicer error message for this case since the order of the arguments isn't obvious and I'm pretty sure I've switched token_address and decimal_places before myself.
