### ISSUE TITLE
ALREADY_EXISTS error for id of maker order after self-match

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1556]
### Steps to reproduce

1. Place order buy 0.1 BTC/LTC 0.1 11
2. Place order sell 0.1 BTC/LTC 0.1 12 -> full self-match
3. Place order buy 0.1 BTC/LTC 0.1 11

### Expected behaviour

Order placed to orderbook

### Actual behaviour

Error: 6 ALREADY_EXISTS: order with local id 11 already exists

### Screens

![Screenshot with xud logs](https://user-images.githubusercontent.com/29906866/81721541-af8df280-9488-11ea-9bab-ce3ecb84083b.png)
![Screenshot with cli output](https://user-images.githubusercontent.com/29906866/81721547-b157b600-9488-11ea-902a-ec524bdfb0a7.png)

**Comment by kilrau** [comment]
Well the id has to be unique, so you should never be able to place two orders with the same id on one node. So unless this is inconsistent, this is expected behavior.

**Comment by kilrau** [comment]
@sangaman ?

**Comment by sangaman** [comment]
Hm so this actually does reveal an inconsistency, you would be allowed to place an order with the same id if you *removed* the order rather than matched it. I don't see anything necessarily wrong with reusing a local order id, it's unusual but I don't think we need to actively disallow it. Remember all order ids so they can't be reused could be a bit of a hassle, even.

I'll fix this logic and ensure that orders removed due to internal match, due to swap, and due to manual removal/cancellation are all treated the same and use the same code. In a sense this is a continuation of #1555, which fixed a different way internal matches were removed differently.

If we want to prevent reuse of local order ids, we can do it in a separate PR, although I personally don't see a need like I said.

Thanks again for detecting this Roman.

**Comment by kilrau** [comment]
Don't see a need to disallow neither. Lets fix it up, and also allow 11 again after match in Romans example. But honestly - we have bigger fish to fry. If this turns out to not be straight forward, lets leave it for now.
