### ISSUE TITLE
UnexpectedClientError during swap when client has not enough lnd funds for swap 

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1558]
### Precondition

Alice has 2 LTC channels with Bob. Local balance of first channel is 0.6 and local balance of the second is 0.9.

### Steps to reproduce

1. Place buy 1 LTC/XUC 2000 1 order as Bob
2. Place sell 1 LTC/XUC mkt order as Alice

### Expected behaviour

If swap can not be performed using 2 channels -> No swap + 'insufficient local balance in channel' error in cli and [ORDERBOOK] log + order of Bob still exists in Alice's orderbook.
If swap can be performed using 2 channels -> successful swap

### Actual behaviour

failed swap + UnexpectedClientError + No order of Bob in Alice's orderbook because of fail.

### Screens
[Screenshot logs](https://user-images.githubusercontent.com/29906866/81942658-120afe00-9603-11ea-89c9-e925870ff774.png)
[Screenshot cli](https://user-images.githubusercontent.com/29906866/81942666-133c2b00-9603-11ea-8895-b546f17100de.png)

**Comment by kilrau** [comment]
As of now this should definitely throw an `insufficient local balance in channel` error. An idea why it's not? @sangaman

**Comment by kilrau** [comment]
> If swap can not be performed using 2 channels -> successful swap
you mean `If swap can be performed using 2 channels -> successful swap` correct? @raladev

**Comment by raladev** [comment]
> > If swap can not be performed using 2 channels -> successful swap
> 
> you mean `If swap can be performed using 2 channels -> successful swap` correct? @raladev

Yeap, my typo, edited.

**Comment by kilrau** [comment]
> it works correctly when u have only one channel (if i have 0.9 balance and tries to fill 1 LTC order), but it seems that the problem of this case is that I have enough balance in sum, but not enough in channels separately .

Correct. And just FYI: "using outbound balance of multiple channels for one payment/swap" is only possible on lightning since the latest lnd 0.10 release. So we can `If swap can be performed using 2 channels -> successful swap` take this requirement out from here and it'll be covered in https://github.com/ExchangeUnion/xud/issues/1562.

**Comment by sangaman** [comment]
Logging a better error message/failure reason is simple enough. The slightly trickier part is handling a failed swap due to insufficient balance so that we return the failed portion of the order to the order book. It makes sense we'd want to do that since we could still fill the order either partly or entirely making several smaller trades.

I can come up with a solution soon, but this issue has me thinking again about an approach where we break down swaps into smaller chunks and execute them in pieces. It would take care of this issue, and also generally make swaps more reliable as well as make trading less susceptible to the free options problem and to the potential perils of large HTLCs. We should discuss this again and maybe make it a goal for an upcoming release, it would take some work and testing but I think would be worth it.

**Comment by kilrau** [comment]
> Logging a better error message/failure reason is simple enough. The slightly trickier part is handling a failed swap due to insufficient balance so that we return the failed portion of the order to the order book. It makes sense we'd want to do that since we could still fill the order either partly or entirely making several smaller trades.

I think this is what this issue should be about. We can assume `insufficient balance` to fail instantly on the `SwapClient` ([connext pending](https://github.com/connext/indra/issues/1125)).

> I can come up with a solution soon, but this issue has me thinking again about an approach where we break down swaps into smaller chunks and execute them in pieces. It would take care of this issue, and also generally make swaps more reliable as well as make trading less susceptible to the free options problem and to the potential perils of large HTLCs. We should discuss this again and maybe make it a goal for an upcoming release, it would take some work and testing but I think would be worth it.

Breaking swaps into smaller swaps with different peers to reduce free option exposure is an entirely different topic indeed. It's a viable approach though and I left a comment mentioning this approach [here](https://github.com/ExchangeUnion/xud/issues/881#issuecomment-629132575) - let's move the discussion there. TL,DR: it's not trivial, since it would give you worse pricing for the sake of spreading trades across multiple peers, but we can consider it mid-term (after June). Let's continue discussing it in the coming weeks.

Justification why not start implementing it sooner:
- reputation scores (and the optional curated list of reliable trading partners) will be good-enough for most peers to swap reliably
- breaking HTLCs into smaller ones to increase routing/payment success is only relevant on lightning for now since connext will be "one channel with the same node" for the coming months
- and even on lightning we are optimizing for a ["one channel with one LSP"](https://github.com/ExchangeUnion/xud/issues/1361) experience in the short term too, in line with the connext experience. So the above "balance in multiple channels" problem won't occur in the default setup.
- for the power market makers who do have more than one lightning channel for the same currency, [MPP will solve using balance of multiple channels](https://github.com/ExchangeUnion/xud/issues/1562), automatically breaking a trade into smaller multiple htlcs via different routes.

**Comment by raladev** [comment]
Update:

It can be reproduced with only one channel using market order

![Screenshot from 2020-06-10 19-31-54](https://user-images.githubusercontent.com/29906866/84379432-78794100-abee-11ea-90fc-b0851ae600b3.png)
![Screenshot from 2020-06-10 19-31-51](https://user-images.githubusercontent.com/29906866/84379434-7a430480-abee-11ea-8379-acae2f48a727.png)

**Comment by kilrau** [comment]
That makes it more serious, but catching this error should be easy. Bumping prio to P2 and next project. What needs to be done: catch this lnd error and display "insufficient balance/couldn't find route with sufficient balance" (we should already have a message for this particular case) in the matching/swap cli output. 

That the marketorder is not really doing market order trying to swap largest possible quantity is captured in a different issue and not high prio as of now: https://github.com/ExchangeUnion/xud/issues/1615

**Comment by raladev** [comment]
1. Lnd throws correct error - insufficient funds. We just need to handle this error on xud side.
[Screenshot from 2020-07-13 14-18-09](https://user-images.githubusercontent.com/29906866/87299167-335d6d00-c514-11ea-89ce-510b978a6b09.png)
[Screenshot from 2020-07-13 14-16-31](https://user-images.githubusercontent.com/29906866/87299170-35273080-c514-11ea-9b9b-3c175566c68c.png)
[Screenshot from 2020-07-13 14-15-50](https://user-images.githubusercontent.com/29906866/87299174-36585d80-c514-11ea-8ab8-fa90e6108158.png)

2.Should the match continue if I get an error about insuff balance? @sangaman

**Comment by kilrau** [comment]
1. Correct, that's what should be done here
2. No, it should not continue. We should add a path in the code for certain error types, like insufficient balance or swap client disconnected, to stop the matching routine.

Agreed? @sangaman

**Comment by kilrau** [comment]
Similar to here, this issue is about xud correctly interpreting and throwing lnd + connext insufficient funds error. Connext depends on https://github.com/connext/rest-api-client/issues/23
