### ISSUE TITLE
Add sync percent and block count to Sync and OutOFSync statuses of getinfo command

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1607]
Reference - status command of xud-docker setup, It seems useful feature for native setup.
![Screen](https://user-images.githubusercontent.com/29906866/84021563-84b29380-a98d-11ea-92fd-716b7ebd49c0.png)

**Comment by kilrau** [comment]
Agree that it would be a useful feature, but we are trying to strictly follow the concept: "xud(L3) controls L2 and L2 controls L1". This allows L1 to be flexible from xud perspective: internal/external/api/btcd/bitcoin core - we don't care.

This feature would require xud to connect directly to L1 which we want to avoid. Our docker setup is like an external service connecting to all layers since and in contrast to xud native, it's a tightly controlled environment knowing all about L1.

While I agree that it is useful, I would not want to do this because of the reason above and in addition because of: we have xud-docker. If you want convenience, use xud-docker :)

**Comment by raladev** [comment]
> Agree that it would be a useful feature, but we are trying to strictly follow the concept: "xud(L3) controls L2 and L2 controls L1". This allows L1 to be flexible from xud perspective: internal/external/api/btcd/bitcoin core - we don't care.
> 
> This feature would require xud to connect directly to L1 which we want to avoid. Our docker setup is like an external service connecting to all layers since and in contrast to xud native, it's a tightly controlled environment knowing all about L1.
> 
> While I agree that it is useful, I would not want to do this because of the reason above and in addition because of: we have xud-docker. If you want convenience, use xud-docker :)

Im not sure but i think lnd should know about percent of synchronization, so we dont need to connect to L1 by xud.

**Comment by kilrau** [comment]
It doesn't expose this properly via an endpoint unfortunately, neither does connext for geth and rather assumes the eth provider endpoint is already synced. Correct me if I'm wrong @erkarl

**Comment by kilrau** [comment]
#wontfix I guess, closing.
