### ISSUE TITLE
connext: balance check on place order

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1609]
EDIT: This is about implementing a connext balance check on `placeorder`.

**Comment by sangaman** [comment]
I can certainly update the `tradinglimits` call for Connext to use our channel balance as the maximum we can sell - I'm guessing that inbound should stay as max number tho?

The second bullet point is a little more involved, we'd need to stop relying on the `ChannelBalance` lnd call since it always includes inactive channel balance. Would we want to switch to the logic for determining trading limits as the new lnd heartbeat call? It will continuously update our trading capacities/limits more precisely than `ChannelBalance` can.

**Comment by kilrau** [comment]
You are right, I was not aware lnd's channelbalance is not separating out inactive balance. Since this makes things complicated and is a magnitude less important, I separated it out into https://github.com/ExchangeUnion/xud/issues/1636 with very low prio. Let's get the connext channel balance check done here first!

**Comment by kilrau** [comment]
> I'm guessing that inbound should stay as max number tho?

Good question, honestly it's tricky. If we use `max number` that basically means no inbound limit but looks very confusing to anyone trying to interpret this super large number. If we are trying to assume a sane inbound liquidity, e.g. local balance x2 it is wrong for sure too. So I guess the cleanest way is to have **no inbound limit** at all.

**Comment by sangaman** [comment]
> > I'm guessing that inbound should stay as max number tho?
> 
> Good question, honestly it's tricky. If we use `max number` that basically means no inbound limit but looks very confusing to anyone trying to interpret this super large number. If we are trying to assume a sane inbound liquidity, e.g. local balance x2 it is wrong for sure too. So I guess the cleanest way is to have **no inbound limit** at all.

I'm not sure how to better reflect no limit in the code/response than with max number. If we want to change something about this let's track it in a separate issue, but I'm honestly not sure how to approach it. We can't just leave it off the response, as it would then take it's default value of 0.

**Comment by kilrau** [comment]
Forgot to add this here: I actually discussed this with Karl today. Its fine as is.
