### ISSUE TITLE
Market Order doesn't fill partially until all available funds are used

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1615]
### Preconditions:
1. taker has 10 ETH in the channel
2. Orderbook - BTC/ETH, Alice - taker (left), Bob - maker(right);
3. Orderbook u can see on screen - 2 Bob's sell orders for 0.3 BTC that cost 12 ETH is sum. 
[Screenshot 2020-06-08 19:20:38](https://user-images.githubusercontent.com/29906866/84059536-72ebe300-a9c3-11ea-8054-4d07bbab4904.png)

### Use case:
1. Alice has ETH balance and wants to buy BTC for whole amount of ETH, but She can not specify ETH amount that She wants to spend
2. So, she decide to use buy 0.4 BTC/ETH mkt with BTC amount, because she calculate approximate sum of btc that she can get.

### Actual Result:
She places the order and got success for 0.2 fill and **error for 0.1 because she have no enough eth to get 0.1 btc fully**. (and 0.1 can not be filled because of empty orderbook)

### Expected result:
0.1 should be filled partially for all avaliable eth amount.

### Steps:
1. fill orderbook as a maker ( sell 0.1 BTC/ETH 60 1, sell 0.2 BTC/ETH 30 2) 
2. fill orders as a taker (buy 0.4 BTC/ETH mkt)

### Logs:

[no_fill_maker.zip](https://github.com/ExchangeUnion/xud/files/4747461/no_fill_maker.zip)
[no_fill_taker.zip](https://github.com/ExchangeUnion/xud/files/4747468/no_fill_taker.zip)

**Comment by kilrau** [comment]
Gotcha. I agree that it should fill up to the latest wei of ETH, but that's not very trivial to do actually since all fees have to pre-calculated down to the satoshi and adjusted if it is not enough. Trial and error doesn't work well atm neither since by default xud removes orders of a peer where a swap failed (though we have a config option to disable this now).

Maybe we'd do better having an "all" flag like `buy all btc/eth mkt`. But since this is a very dangerous functionality, I'd say let's pick this up again in the next project where we optimize things (assiged).

**Comment by kilrau** [comment]
> Maybe we'd do better having an "all" flag like `buy all btc/eth mkt`. But since this is a very dangerous functionality, I'd say let's pick this up again once we are out of the woods.

This is implemented in https://github.com/ExchangeUnion/xud/pull/1922 . Closing here.
