### ISSUE TITLE
Local xud stale orders

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#165]
On a maker order, when the swap is to be initiated by a remote node, client can trigger order cancellation on `xud`, and even if it won't reach the remote node on time, it will be cancelled on the local `lnd` node, so swap execution will fail. But there's a small chance that even the local `xud` won't be updated on time (despite the short latency), so swap will be executed on a stale order from the client perspective. A solution for this will be to pause the swap execution when it reaches the local `lnd` node, and to actively query the client for the order status. To support this, changes to `lnd` will be required. 

Not sure if we'll ever want to address this scenario. 
Also, need to check for equivalent problem/solution on Raiden swaps.

**Comment by sangaman** [comment]
Seems like it would be pretty complex to implement, the client would need to provide a service that quickly confirms if an order is still valid before it being swapped? I'm also not sure how much of an improvement that would be, since it's technically possible that they confirm an order is invalid, then moments later it is canceled while the swap is in progress. If the client notifies us immediately when an order is canceled, I think that's about as good as we can hope to achieve.

**Comment by kilrau** [comment]
Duplicate. Closing in favor of https://github.com/ExchangeUnion/xud/issues/587
