### ISSUE TITLE
More descriptive error message for "alias CheeseMonkey is unknown"

### ISSUE THREAD

**Issue by peartobear** [ExchangeUnion/xud#1670]
A more descriptive error message in lines with LND's `lncli` wordings would reduce confusion. 

Current:
`Error: 2 UNKNOWN: failed to open BTC channel for 10000000 with CheeseMonkey: alias CheeseMonkey is unknown`

Proposed:
`Error: 2 UNKNOWN: failed to open BTC channel for 10000000 with CheeseMonkey: peer not connected`

**Comment by sangaman** [comment]
Would it make sense to say "node not found" or "peer not found" rather than "not connected"?

Saying "not connected" to me sounds like the only issue is that we're not connected to that node at the moment, as opposed to being a node/alias we don't even know exists. So the "not connected" message could be used but only when we know the node but aren't connected.

**Comment by kilrau** [comment]
I am fine with the proposed `not connected` for **both**: not connected, but known (previously connected) nodes as well as never-connected (unknown) nodes. Just sounds a notch easier to implement. If it's a quick win to make a distinction as you describe, go ahead!

**Comment by sangaman** [comment]
> I am fine with the proposed `not connected` for **both**: not connected, but known (previously connected) nodes as well as never-connected (unknown) nodes. Just sounds a notch easier to implement. If it's a quick win to make a distinction as you describe, go ahead!

We already have a separate error for when a node exists but isn't connected, so no changes needed to keep this behavior. I'm just changing the message for when we get an alias that we can't find a node for.
