### ISSUE TITLE
Wallet initialization msg appears when there is no initialized wallets.

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1675]
**Precondition**
2 initialized lnd nodes with wallets

**To Reproduce**
1. Perform xud installation setup with wallet creation

**Actual behavior**
"The following wallets were initialized:" with no wallets 

**Expected behavior**
No "The following wallets were initialized:" msg + list of wallets that can not be initialized.

**Comment by kilrau** [comment]
For now this should be the expected behavior:
Warm up check makes sure all clients are ready (catches 99.95%), if clients cant' get ready within 3 minutes, xud-docker should throw and ask the user if he wants to continue without swap client x. That's the behavior we already try and it has to be refined.

If clients were ready but crashed/became unresponsive during the create process then xud itself would need to record which clients were there in the beginning and which ones were successfully created. Since that scenario is pretty unlikely and the effort quite huge, I wouldn't want to do that.
