### ISSUE TITLE
`tradinglimits` should account for "reserved balance"

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1678]
### How it is

Currently, calling `tradinglimites` calculates & displays **total** inbound and **total** outbound channel capacity for a respective assets' channel:

```
simnet > tradinglimits

Trading Limits:
┌──────────┬───────────────────┬──────────┐
│ Currency │ Max Buy           │ Max Sell │
├──────────┼───────────────────┼──────────┤
│ BTC      │ 2.5               │ 2.5      │
├──────────┼───────────────────┼──────────┤
│ ETH      │ 90071992.54740991 │ 10       │
├──────────┼───────────────────┼──────────┤
│ LTC      │ 5                 │ 5        │
└──────────┴───────────────────┴──────────┘

```

### How it should be

Max Buy/Max sell is reduced by quantity reserved quantity for open orders. We have a separate issue for calculating "reserved balance" and displaying it under `getbalance` already: https://github.com/ExchangeUnion/xud/issues/1584

**Comment by sangaman** [comment]
As just discussed, the plan for resolving this issue is:

1. Remove reserved order amounts from `GetBalance` - reversing #1584.

2. Subtract reserved order amounts from the max buy and max sell amounts on the `TradingLimits` call, e.g. if we have outbound capacity of 1.2 ETH, but we have an order to sell 0.7 ETH, our max sell would be 0.5 ETH.

3. Return reserved order amounts on the `TradingLimits` rpc call.

4. Reject orders that would put our total reserved balance over our total capacity. An exception to this would be for inbound limits for Connext currencies, since we have the ability to dynamically request additional inbound collateral via our "lazy collateral" approach.

5. Revisit the logic used for accepting market orders as it pertains to our trading limits, we want to ensure that market orders won't make it so that they don't leave us with insufficient balance to cover our outstanding orders.

I'm going to start on this ASAP, points 1-3 above are informational in nature whereas 4-5 changes the way we validate new order placement requests. I'll probably wind up implementing those in separate PRs.

**Comment by sangaman** [comment]
I'm going to open a separate issue for 4 & 5, this issue will just track returning the proper values for the `TradingLimits` call but not how we enforce limits on the `PlaceOrder` call.
