### ISSUE TITLE
Fix alias collisions

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1688]
### Background

We are seeing alias collisions frequently https://github.com/ExchangeUnion/xud/issues/1687 , especially on travis. Since statistically this is extremely unlikely to happen, this issue is about finding and fixing the root cause of such.

**Comment by hatmer** [comment]
This was expected due to the [Birthday Effect](https://www.dcode.fr/birthday-problem): we chose a word list of length 2048, so if we generate say 100 aliases then the chance of two (if not more) aliases being the same is 91%. The solution is to use three words in the alias, or tacking on a number at the end, in order to increase the number of combinations.

**Comment by hatmer** [comment]
So I counted wrong: there is a 91% chance that two or more nodes will have the same first word. The chance that those same nodes also have the same second word is around .05%, and so 91 * .05 = 4.55% chance of a collision in any set of 100 aliases. This could be the source of the problem, so I will modify the aliases to have `FirstSecond-123` format and see if that helps.
