### ISSUE TITLE
Taker order fee (3-way atomic swap)

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#174]
XUC fee should be paid after the swap. If a taker peer didn't pay it, he should be penalized.
Making the fee payment atomic together with the swaps seems to be too complicated and not particularly necessary, due to the low payment amounts, in addition to having a reputation system.

**Comment by kilrau** [comment]
The goal is indeed to do it in the same atomic swap. Otherwise the our protocol is not completely trustless. The reputation system is only for failed connects or locked up funds, but under no circumstances is it acceptable that funds get lost (which is the case if a taker doesn't pay its fee).  Currently evaluating this with @offerm

**Comment by offerm** [comment]
I think this is doable as part of the swap (using the new swap approach).

**Comment by kilrau** [comment]
Assigning to you the beta release @offerm

**Comment by kilrau** [comment]
Waiting for Raiden swaps (https://github.com/ExchangeUnion/xud/issues/106)

**Comment by kilrau** [comment]
As discussed, XUC will be taken out of the protocol itself. We'll use the native BTC/LTC/ERC20 of the underlying pair as liquidity incentive. No 3-way swap necessary.
