### ISSUE TITLE
Swap recovery stopped monitoring active payment

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1749]
**What happened?**
1. Received BTC payment
2. Sent ETH
3. ETH payment was not claimed - swap timed out
4. xud started monitoring ETH payment for the status
5. xud was restarted couple of times

After checking the `xud.db` manually the deal was in state 1 (SwapState.Error).

With the current implementation swap recovery is only started for active deals:
```
    const swapDealInstances = await this.repository.getSwapDeals();
    swapDealInstances.forEach((deal: SwapDealInstance) => {
      this.usedHashes.add(deal.rHash);

      if (deal.state === SwapState.Active) {
        this.swapRecovery.recoverDeal(deal).catch(this.logger.error);
      }
    });
```

The question is why/how did the deal get error state?

Full xud logs:
[swap-recovery-report.log](https://github.com/ExchangeUnion/xud/files/4968965/swap-recovery-report.log)

**Comment by kilrau** [comment]
P1 just to find out what happened and make sure it's indeed a very edgy edge case.

**Comment by sangaman** [comment]
I think I've figured out the issue. Even though the maker isn't failing the deal due to timeouts, he receives a swap failed packet from the taker when the taker fails it due to timeout.

We aren't failing deals (due to a received swap failed packet) when we're in the preimage resolved or payment received phase, but I think we need to also update this to not fail when we're sending payment *and* we're the maker. That should prevent the scenario above from happening.

```typescript
if (deal.phase === SwapPhase.PreimageResolved || deal.phase === SwapPhase.PaymentReceived) {
  // we don't want to fail a deal if any one of its payments is already completed
  this.logger.warn(`received swap failed packet for deal in phase ${SwapPhase[deal.phase]} with payment hash ${rHash}`);
  return;
}
```

I'll open a PR shortly.

**Comment by kilrau** [comment]
We saw this happening today.
- swap where maker was sending ETH failed.
- xud continued monitoring, but after restart stopped monitoring the swap.
- looking into the db after this, the swap state was `1` (errored).
- connext eth htlc was still up, without `status` field.

In general we might want to have a closer look into recovery since it looks like we make exceptions where *not* to fail. Maybe we should consider doing it the other way around.

**Comment by sangaman** [comment]
> In general we might want to have a closer look into recovery since it looks like we make exceptions where _not_ to fail. Maybe we should consider doing it the other way around.

I can do that, it could help with any future changes to the swap phases. But I think the logic in the PR above is correct for now.
