### ISSUE TITLE
Prevent a node from being connected to itself

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#177]
Make sure a node won’t get connected to itself, nor saving itself in the host list. It’s a likely scenario when querying other peers for their list of peers (#147), but it can also happen by mistake, when initiating a connection manually. 
We might just want to check if before attempting to add a new outbound connection, and not in a new inbound connection, because the same node will control these two sides. 

#181 is a prerequisite.

**Comment by michael1011** [comment]
Another approach would be not allowing connections to nodes with the same public key as your own node. But this should be used as last resort and for edge cases because it requires the handshake to happen. 

I propose blocking connections to your external IP and P2P port and blocking the same public for everything else.

**Comment by sangaman** [comment]
We can put in a check for public key, but as @michael1011 says it's an edge case and can only happen after handshake. I think it's best to catch this before the handshake begins. But it sounds like there's agreement on only checking to stop connections to our own IP **and** listen port, otherwise allow the connection. Like @kilrau says it's possible for two nodes to have the same external IP even when running on separate machines.

**Comment by moshababo** [comment]
Agree, we need to apply this to both internal/external IP address + listenPort. 

We can add `nodePubKey` check as well, in case we missed it. Although last time I checked, trying to connect to yourself via external IP leads to immediate disconnection.

**Comment by kilrau** [comment]
As a sidenote, we allow adding 'localhost' or own 'IP' into the host table, but filter on connection attempt:
![image](https://user-images.githubusercontent.com/19181985/43419753-b50aee96-93f6-11e8-856b-1d323c9e2be2.png)

**Comment by kilrau** [comment]
And just FYI: we already have the case where 2 xuds are behind the same domain (0.tcp.ngrok.io) but get identified by different ports ;)

**Comment by michael1011** [comment]
What I am thinking right now is: 

1. check if the IP and port you want to connect to are your own ones: #181. If that is the case don't even try to connect
2. if the public key of the peer is the same as your own disconnect immediately because you are trying to connect to yourself

**Comment by offerm** [comment]
point 2 is a must.
point 1 is nice to have. 

The value that we gain from 2 is huge regardless of 1.

IMHO, it should be done asap.

Offer

**Comment by kilrau** [comment]
Yes, let's do both, 1+2 https://github.com/ExchangeUnion/xud/issues/177#issuecomment-411369865 @michael1011 @offerm

**Comment by kilrau** [comment]
Who did put the pubKey into the handshake now btw? Kudos for that, we should have done this way earlier.
