### ISSUE TITLE
Verify that my own xud is reachable  

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#182]
If listening to P2P connection, verify that `listenPort` is reachable by the node's external IP. 
If it's not alert that the node is not reachable. 

#181 is a prerequisite.

**Comment by kilrau** [comment]
notification enough

**Comment by kilrau** [comment]
If result is 'not reachable', print notification (don't shutdown!):
```
{Port 8885 is not reachable, trying different port}, auto-switch xud port to 443
{Port 443 is not reachable, trying different port}, auto-switch xud port to 80
{Port 80 is not reachable, please check your firewall configuration and restart xud}
```
If one of these is successful:
`{Port 443 is reachable and is now your advertised port for incoming connections}`

**Comment by kilrau** [comment]
Please let me know what you think @moshababo @sangaman @offerm @michael1011

**Comment by sangaman** [comment]
I'm actually not sure I follow this issue, is this about verifying the listening addresses that peers share with us on handshake? Why would we try something besides what they shared with us?

**Comment by kilrau** [comment]
This is about verifying, that my **own** externalIP+Port is reachable.

**Comment by sangaman** [comment]
Ah thanks for clarifying, so it's something we would do just once on startup.

**Comment by offerm** [comment]
I think that we should avoid guessing. for sure not without the user asking us to do so.

We can have default values for listen port and for connect port but we should not "guess" other values in case these are not reachable.

If the user configures XUD to do so, It is OK to detect our IP external address (that may change due to the ISP, without the user involvement). There is no reason to auto-detect the port since this is not dynamic.

If reliable, we can try to verify the host:port XUD advertise.
 
LND and BTCD are working good for a large community.  I see no reason to do something else.

Beside the external IP being changed (not in the user control) these are setup issues that should be debugged and resolved by the user. No need to resolve that for him.

**Comment by kilrau** [comment]
moved 80/443 part into https://github.com/ExchangeUnion/xud/issues/345

**Comment by moshababo** [comment]
@offerm  

> We can have default values for listen port and for connect port but we should not "guess" other values in case these are not reachable.

Which other values are you referring to?

**Comment by moshababo** [comment]
@offerm  

> We can have default values for listen port and for connect port but we should not "guess" other values in case these are not reachable.

Which other values are you referring to?

**Comment by offerm** [comment]
443 and 80.  (what about 8080 :-) )
Don't think we should try these ports as fallback. There is a high probability of these ports to be open but not related to xud.

**Comment by moshababo** [comment]
I'm not sure I understood your comment in the overall.

The point here is to alert the user in case his node is not reachable, assuming that he doesn't know about it.
You're saying that out detection wouldn't be reliable, or that we shouldn't bother to alert about it?

**Comment by kilrau** [comment]
You didn't understand my comment or @offerm s? I did back down with the alternative ports (for now) and shifted the discussion to a later stage. This issue is solely about
a) checking if my OWN externalIP+Port is reachable and
b) if not, alert as per https://github.com/ExchangeUnion/xud/issues/182#issuecomment-413043575

That's it. Simple issue :)

**Comment by moshababo** [comment]
I was referring to @offerm's [comment](https://github.com/ExchangeUnion/xud/issues/182#issuecomment-413106853)
