### ISSUE TITLE
[Concept] Private Key encryption

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#184]
On first `xud` start;
1. Create `nodePubKey` & private key (in `nodekey.dat`) (#39, done)
2. Ask user on first xud launch {Please set a password for xud. This will ensure that only you can use your public xud identity (PublicKey) and others can't pretend to be you:}, offer to {skip} encryption with explainer a la {You can skip this, but this increases the risk of someone else being able to impersonate you. Still skip?} {Y/n} 
3. Confirm password
4. Show 24 word recovery phrase (https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki), ask to store it somewhere
5. Confirm random 3 out of 24 recovery words
6. Store encrypted, ask for password on every xud bootup.

**Comment by kilrau** [comment]
What do you think @sangaman @moshababo @offerm ?

**Comment by michael1011** [comment]
I wouldn't ask the user but enable the encryption by default and let the user disable it by a command line argument or config value similar to the way LND does it.

For the case of XUD getting demonized there should be the option to input the key via xucli (also similar to the way LND does it). 

And why would we need a BIP 39 recovery phrase? We have just a single private key to backup and BIP 39 is meant for BIP 32 hierarchical deterministic wallets as far as I know. Backing up the `nodekey.dat` file or its plain text content should be sufficient. 

@kilrau

**Comment by offerm** [comment]
I Have a question: What is the consequence of losing access to this file (for whatever reason - forgot the passphrase, lost the file itself, etc)?

If we just create a new file in that case what are the implications?

**Comment by sangaman** [comment]
@offerm The idea longer term is a sort of decentralized reputation system along with a way to burn or stake XUC and tie that to a particular key, such that there's a cost associated with creating keys. Losing your key basically loses your identity/reputation.

We definitely don't need a BIP39 recovery phrase, like @michael1011 said we don't need any deterministic generation of keys since we only have one. I suppose we could create some mnemonic from the entropy used to create the node pubkey but I don't think it's really needed.

**Comment by kilrau** [comment]
Challenging question: how do we include recovery for btcd, ltcd, geth into ONE recovery phrase?

**Comment by michael1011** [comment]
@kilrau `btcd` and `ltcd` don't include a wallet by default so I think you mean the wallets in the LND instances?

My first though would be using a different derivation path for each wallet but I am not sure if LND does support that.

**Comment by sangaman** [comment]
I think that's a very challenging question indeed. It should be possible for lnd to have one recovery key for each wallet on each chain, but since we're now using multiple lnd instances we'll necessarily have multiple wallets and multiple recovery phrases. You can't roll those into a single recovery phrase because they were generated completely separately, not deterministically from each other. Same for the geth account recovery, those keys are generated totally separately. I think you'd need a way to get all of them to use the same entropy, maybe if they let you provide your own entropy instead of generating it randomly, i don't know off the top of my head if that's a feature for all the applications involved.

**Comment by kilrau** [comment]
Thanks for the feedback, after some digging yes indeed this needs a bit more discussion. 

What I could think of is the approach to generate all keys via https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki (& https://github.com/satoshilabs/slips/blob/master/slip-0044.md) ourselves (via some libraries, multi-coin wallets like coinomi do it like this) and then potentially import it into lnd/raiden. But seems this is not supported yet.
