### ISSUE TITLE
Unable to add our currency for swap.

### ISSUE THREAD

**Issue by DarshanCLila** [ExchangeUnion/xud#1993]
We have Politicoin, our own currency that we would like to setup for swap.
Currently I cannot find a way to add my own currency that enables swap with other currencies.
Has someone done that and can guide on it?

**Comment by kilrau** [comment]
That is a known issue that other users have brought up in the past, we are working on it, could you please confirm that the issues you ran into are covered in https://github.com/ExchangeUnion/xud/issues/1932 ? If so, you can close here.

Since adding your own token to OpenDEX is not trivial from a technology perspective, could you read through [this issue](https://github.com/ExchangeUnion/xud/issues/1956) and see which option would work for you?

**Comment by kilrau** [comment]
Could you please check if above linked two issues cover your use case? @DarshanCLila If not, please elaborate and reopen. Closing for now.
