### ISSUE TITLE
[Discussion] Socket connection can be opened twice

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#271]
At least worth discussing: If I have an open connection from my `localhost` to e.g. `xud1.test.exchangeunion.com`, `xud1.test.exchangeunion.com` allows me to open a new connection back to my `localhost`. Ergo, I end up with 2 independent socket connections. Not sure if that's desirable and leads to unwanted behavior.

Also, ping pongs only show on the initiating side of the socket connection, IMO they should show on both ends since this connection can be used by both parties.

**Comment by moshababo** [comment]
In this case, one of the connections is inbound and the other is outbound. We can correlate between the ports only after the handshake, assuming that `listenPort` is advertised and is correct. Otherwise we can use `nodePubKey` instead.

In regards to ping pongs: both sides of the connection are initiating pings. Do you see it only on one side?

**Comment by sangaman** [comment]
Using nodePubKey will prevent this. That'll be taken care of with the host/peer restructuring.

**Comment by kilrau** [comment]
K, since you want this (#256 ) to be merged for prealpha.1, we'll revisit this discussion in our Tuesday call

**Comment by offerm** [comment]
@kilrau Are you sure you have 2 connections? Not clear how xud1.test be able to connect with your "localhost".  Aren't you behind NAT/FW?

**Comment by kilrau** [comment]
Will be solved #185 , test again when this is merged
