### ISSUE TITLE
`host id is missing` errors

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#288]
`host ID is missing`

nodePubKey is not provided in all messages!?

**Comment by sangaman** [comment]
This is simply the message that gets logged when a peer that's disconnected doesn't have a known hostId. This would happen if the handshake wasn't completed for instance.

But yes, nodePubKey is not currently what's used for the host id and we're using dummy values for it (which is fixed in #243). We have a lot of changes slated for host/peer structure. I figure this message can just be dropped since it's not really necessary or informative, but I'll take care of it as part of other the broader changes since it's not actually a bug.
