### ISSUE TITLE
Solve docker issues

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#297]
1. "Segmentation fault"
2. "New release -> trigger travis build -> push to dockerhub -> deploy onto google kubernetics

**Comment by itsbalamurali** [comment]
@kilrau 
Apologies for the delays:
1. Segmentation Faults are not occurring anymore, i am assuming that this is due to latest code changes to `xud`.
2. Docker builds are already automated as you can see here: https://hub.docker.com/r/exchangeunion/xud/builds/
3. Once the docker-ltcd PR is merged and our lnd swap resolvers are setup i will be automating depolyments onto our GCP GKE AKA Kubernetes.
