### ISSUE TITLE
[Concept] Update network on IP/Port change

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#314]
New message format: update peers on new IP+Port combo for updating e.g whitelists (or blacklists ;), signed.

Update my own external IP via (regular?) checks.

**Comment by sangaman** [comment]
We have discussed being able to update handshake data, and I think that would cover this.

**Comment by kilrau** [comment]
What I mean is something like:
- `xud` regularly checks its external IP & Port
- if it detects a change, it changes it's advertised IP & Port and pushes this via a new message format to peers

**Comment by sangaman** [comment]
That would conflict with the approach of having the user specify external IP addresses in the config. Also I don't think it can check it's external port per se. Plus as far as I know IP address shouldn't change during a connected session, if it did we'd lose all our connections as far as I know.

**Comment by kilrau** [comment]
I see what you are saying, I'll think about it a bit more.

**Comment by michael1011** [comment]
Appending your external IP and default listening port to the already specified addresses in the config on startup would make sense for convenience reasons. Although even that should be optional for the sake of privacy.

**Comment by sangaman** [comment]
Yeah I'd prefer that the automatic listening address is only used if the user didn't specify any in the config file, because there's no guarantee that external IP + listening port is valid. I still think it's better than nothing for a default if nothing is specified though, but if they go through the trouble of specifying something we should just use that.

If they don't want to advertise any listening addresses but still want to listen, they can put in an empty array for `p2p.addresses`. Maybe that should be pointed out in the readme.

**Comment by kilrau** [comment]
Alright, looks like we are covered. Nothing specified: IP + Port detected, if specified we'll use that.
