### ISSUE TITLE
Allow to listen to Incoming P2P connections, but NOT advertising.

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#366]
test, if it doesn't work - flesh out a bit and move to alpha.2 @offerm

**Comment by sangaman** [comment]
It shouldn't work now, since #317 automatically adds a listening address if none are specified and we are listening. This could be resolved in a couple of ways - maybe we only automatically add an address if 

It should be noted that the downside of this would be that peers who connect to you won't automatically reconnect to you, because they won't be told your listening address. The solution would be to add to the listening addresses in the db whichever host/port we successfully used to create an outbound connection, if it's not included in the advertised addresses.

Part of me does question if this is actually necessary tho, why would you listen for incoming connections if you're not going to share your listening address? We will have other measures down the road to prevent undesired nodes from connected to you. One option, for example, is to only accept connections from known nodes.

**Comment by offerm** [comment]
What I'm checkin is the follow:

I have node A and node B listening on 8885 and 8895.
I connect A to B via `xucli  connect 0245780f9b2e6b7047cbe4d61c2b6d7434cc63c943dcd62c7ac604f936c76ed1c4 localhost 8895`

After a restart, they are not getting reconnected.

IP address is properly detected and I can see in the log
`retrieved external IP: 84.111.139.147`

Checking the `nodes` database table I see that both recorded a record for the peer but the `addressTest`is [].  This is causing them not to reconnect on startup.

I looked at the code and the problem is in lines 108-109 of pool.ts
```
    this.handshakeData = handshakeData;
    this.handshakeData.addresses = this.addresses;
```
The second assigment overide the detected address.

Let me know when fixed and I will try again (don't think I will manage to connect them....).

**Comment by offerm** [comment]
Better to separate the fix of this problem from the change of to the URI format.

@sangaman when do you plan to integrate #372? If this takes time we better fix the problem with a separate PR.

**Comment by sangaman** [comment]
I just finished reviewing it. Moving the fix into a separate PR would make sense, but I'm also fine with leaving it as is since I don't think it's urgent and the work was already done and it's related to the other changes in the PR. Up to @michael1011 I'd say, I'm fine either way.

**Comment by kilrau** [comment]
Good analysis and questioning of the use case @sangaman After thinking about it for a bit, I think there is a tiny use case, but with low priority. Moved to `1.0.0`.

I see it that way:
1. Blacklist = `ban` used by reputation system for nodes which were unreliable or manual ban e.g. nodes from certain regions because of legal requirements or just because I don't like node X. "Share my orders with everyone, but the following nodes." (https://github.com/ExchangeUnion/xud/issues/336)
2. Whitelist = Legal requirements require me to e.g. only share orders with other exchanges regulated by the same regulator "Share my orders with the following nodes only." (https://github.com/ExchangeUnion/xud/issues/179)
3. Don't advertise = I'm running `xud` but don't want everyone to know my orders but some selected group. Use case I can think about is for developers or exchanges testing on the www before going live, not wanting to manually white-list all pubkeys in their test environment, but just use the known `PubKey@IP:Port`. It's just easier to use for tests than looking up `nodePubKeys` and manually whitelisting them. "Share my orders with everyone who knows my `PubKey@IP:Port`" .

**Comment by sangaman** [comment]
For case 3 where I only want to connect to specific peers but they're not in my database currently, couldn't I just connect to them directly? There's also the risk that my listening address is leaked and now anyone can connect to me.

**Comment by michael1011** [comment]
Yeah you are right. I will open a separate PR just for the fix. @sangaman @offerm

**Comment by offerm** [comment]
So, with latest master, after removing the seed nodes I connected my two LNDs A and B using

`./bin/xucli  connect 0245780f9b2e6b7047cbe4d61c2b6d7434cc63c943dcd62c7ac604f936c76ed1c4@localhost:8895`

All looks well.

The nodes table of A has one record
```

+----+--------------------------------------------------------------------+-----------------------------------------+--------+---------------------+---------------------+
| id | nodePubKey                                                         | addressesText                           | banned | createdAt           | updatedAt           |
+----+--------------------------------------------------------------------+-----------------------------------------+--------+---------------------+---------------------+
|  5 | 0287b085247689e51ff6230cb3527410743e2730403c342ff46557705154ae7dc2 | [{"host":"84.111.139.147","port":8885}] |   NULL | 2018-08-22 19:31:51 | 2018-08-22 19:31:51 |
+----+--------------------------------------------------------------------+-----------------------------------------+--------+---------------------+---------------------+
```

The nodes table of B has one record

```
+----+--------------------------------------------------------------------+-----------------------------------------+--------+---------------------+---------------------+
| id | nodePubKey                                                         | addressesText                           | banned | createdAt           | updatedAt           |
+----+--------------------------------------------------------------------+-----------------------------------------+--------+---------------------+---------------------+
|  5 | 0245780f9b2e6b7047cbe4d61c2b6d7434cc63c943dcd62c7ac604f936c76ed1c4 | [{"host":"84.111.139.147","port":8895}] |   NULL | 2018-08-22 19:31:51 | 2018-08-22 19:31:51 |
+----+--------------------------------------------------------------------+-----------------------------------------+--------+---------------------+---------------------+

```

After restart they are unable to conenct.....

Restrat itself take a long time while `xud` tries to open a connection.
The conenction failed since I'm behind NAT and not accesable for the internet.
Still, my two local `xud` should be able to connect as they are on the same machine.....

**Comment by sangaman** [comment]
> Restrat itself take a long time while xud tries to open a connection.

Yeah currently we wait for all connecting to be reestablished to peers, which is normally quite fast but can take 5-10 seconds if there are timeouts. I've thought about removing this wait and just letting the connections resolve after the xud server is up and ready. 

I will test this myself when I have some time and report back, it certainly *should* be connecting based on what you've posted. Do you get any errors in the logs that might be helpful?

**Comment by offerm** [comment]
I'm getting 
`8/22/2018, 10:37:01 PM [P2P] warn: error while opening connection to peer 0245780f9b2e6b7047cbe4d61c2b6d7434cc63c943dcd62c7ac604f936c76ed1c4: Connection timed out.`

As I wrote, connecting via my external IP can't work since I'm behind NAT. 
Connection restore should be via localhost as it was done when  I used the xucli to connect them.

**Comment by sangaman** [comment]
Ahhh right - I think then this would be addressed by #365. But I think for now if you want this to work you should specify the localhost listening address in the config, then the peers will know to connect using that address.

**Comment by kilrau** [comment]
> Yeah currently we wait for all connectons to be reestablished to peers, which is normally quite fast but can take 5-10 seconds if there are timeouts. I've thought about removing this wait and just letting the connections resolve after the xud server is up and ready.

Thx @offerm @sangaman , we definitely want to do this, not super urgent tho: https://github.com/ExchangeUnion/xud/issues/387

**Comment by kilrau** [comment]
Main topic of the issue "Allow to listen to Incoming P2P connections, but NOT advertising" will be closed by https://github.com/ExchangeUnion/xud/issues/434
