### ISSUE TITLE
Add wallet rpc methods and integrations

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#40]
Allow for creation of new deposit addresses and for withdrawals through xud.

**Comment by sangaman** [comment]
Partly solved by #94, still need to add appropriate rpc calls.

**Comment by kilrau** [comment]
I think we are ready to do this now. Volunteers? @ImmanuelSegol @erkarl

**Comment by sangaman** [comment]
We have the code to create a new deposit address in lnd, still need a wrapper method to send coins in lnd but that is easy. Then we'd need wrapper rpc methods for these which also shouldn't be hard. I think this should be low priority, but maybe we should discuss whether we'd want `xud` to be the sole point of interaction that manages all the `lnd` instances entirely, or whether it's ok to let some calls be made directly on `lnd`.

**Comment by ImmanuelSegol** [comment]
> I think we are ready to do this now. Volunteers? @ImmanuelSegol @erkarl

I would be happy to take this @kilrau

**Comment by kilrau** [comment]
I'd be pro `xud` being the sole point of interaction to reach a certain abstraction.
* only expose calls that matter, cleaner
* enables a much nicer CLI experience (compare https://sparkswap.com/docs/getting-started/first-use)
* enables us to switch/add support of different implementations like c-lightning

**Comment by kilrau** [comment]
You got it @ImmanuelSegol

**Comment by ImmanuelSegol** [comment]
@kilrau  @sangaman Which methods should I implement?

**Comment by kilrau** [comment]
Hold-off on this. I would like to finalize testing bitcoind and litecoind first and then list calls here.

**Comment by ImmanuelSegol** [comment]
@kilrau Could I get a better description of which methods exactly I should implement?

**Comment by kilrau** [comment]
Yes, of course. Relevant for the wallet usage are [LND](https://api.lightning.community)'s:

https://api.lightning.community/#genseed
https://api.lightning.community/#initwallet
https://api.lightning.community/#unlockwallet
https://api.lightning.community/#changepassword
https://api.lightning.community/#walletbalance
https://api.lightning.community/#gettransactions
https://api.lightning.community/#transactiondetails
https://api.lightning.community/#estimatefee
https://api.lightning.community/#listunspent
https://api.lightning.community/#sendcoins
https://api.lightning.community/#sendmany
https://api.lightning.community/#newaddress
https://api.lightning.community/#subscribetransactions

but since this already covers quite a good portion of LND's rpcs, I'd want to discuss if it doesn't make sense to [integrate all of them](https://github.com/lightningnetwork/lnd/blob/v0.5.2-beta/lnrpc/rpc.proto) and work on some tests to check if everything still works after we upgraded LND to a new version. More responsibility for us, but a major step towards our vision "user/developer doesn't have to care about underlying clients".

[Raiden](https://raiden-network.readthedocs.io/en/latest/rest_api.html) doesn't seem to provide interfaces for the underlying full node at all!? So directly call [geth interfaces](https://github.com/ethereum/go-ethereum/wiki/geth)?

**Comment by kilrau** [comment]
@erkarl @sangaman @offerm

**Comment by erkarl** [comment]
I'm not completely sold on the idea of exposing all the layer2 client calls via our gRPC. The benefit vs accessing the layer2 client directly would be that it's transport happens gRPC instead of a mix of REST/gRPC etc. The user would still need to familiarize themselves with the underlying layer2 client API. I'm also wondering how much maintenance overhead it would cause.

Wouldn't it be more convenient for the end user to access xud's interface instead? Given a non-xud feature - would it make sense to host that layer2 client in isolation?

**Comment by kilrau** [comment]
> Given a non-xud feature - would it make sense to host that layer2 client in isolation?

Hmm ok, good point. So what's your verdict? Don't go for it all or only integrate the layer2 client calls we actually need?

**Comment by erkarl** [comment]
I'd go for the latter - only implement calls that xud needs to provide its features. Exposing those calls could be done via xud's unified interface. The value proposition would be that the developer integrating/using xud wouldn't have to learn all layer2 clients' APIs - only xud's API.

**Comment by kilrau** [comment]
Closing as per https://github.com/ExchangeUnion/xud/pull/889#issuecomment-488237527
