### ISSUE TITLE
xucli buy/sell commands

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#404]
```bash
xucli buy <pair_id> <quantity> limit <price>
xucli sell <pair_id> <quantity> limit <price>
xucli buy <pair_id> <quantity> market
xucli sell <pair_id> <quantity> market
```

our beloved `xucli`, a never ending story :)

**Comment by sangaman** [comment]
One minor thing I'd prefer is having order commands start with quantity and pair ID next. "buy 5 litecoin" follows language patterns. Then another thing is for limit orders instead of having to type out "limit" maybe just have the price. That way we also have the same number of arguments for both market and limit orders. So it would be:

```bash
xucli buy 5 LTC/BTC market
xucli buy 5 LTC/BTC 0.01
xucli sell 5 LTC/BTC market
xucli sell 5 LTC/BTC 0.01
```

I also think it would be nice to accept either "market" or "mkt" for market orders as the last argument, for less typing.

**Comment by kilrau** [comment]
Nice! @sangaman 

I tried around building a sentence first too and honestly the direction of the pair might be the one last thing ppl get confused with every now and then (and a `/` is not nice to type neither) so I'm adding another alternative.

Summary:

```
xucli buy 5 LTC/BTC market
xucli buy 5 LTC/BTC 0.01
xucli sell 5 LTC/BTC market
xucli sell 5 LTC/BTC 0.01
```

Alternative:
```
xucli buy 5 LTC for BTC market
xucli buy 5 LTC for 0.01 BTC
xucli sell 5 LTC for BTC market
xucli sell 5 LTC for 0.01 BTC
```

Also all "market" can be replaced with "mkt".

**Comment by sangaman** [comment]
I thought about something like this too but it feels like a little verbose and it doesn't follow the command line argument conventions that I'm used to - e.g. having a word in there (`for`) that does nothing. Another issue is that "buy 5 LTC for 0.01 BTC" sounds like you might be paying 0.01 btc total for all 5 ltc.

**Comment by kilrau** [comment]
Yeah, let's go with yours @sangaman
