### ISSUE TITLE
Remove `executeSwap` command from CLI

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#416]
Just for (Berlin) demo purposes

**Comment by offerm** [comment]
Best to leave the command in and hide it from the list.

To be done AFTER Berlin.

**Comment by sangaman** [comment]
To me, the cli command itself is not a big dea. I'd want to remove the `executeSwap` code from xud though so as not to have to maintain it and to be able to pare down the deal packets from repeating data that's specified by the order, and treating the orderId as a non-nullable field for deal requests. I'm in favor of removing the call entirely, but it's not urgen it offer or anyonen else has plans to use it in the foreseeable future.

**Comment by kilrau** [comment]
@offerm you are the decision maker here, please let us know if you'll use it, then we'll keep it

**Comment by offerm** [comment]
@sangaman @kilrau the only reason to keep this has to do with our planned swap protocol change. My concern is that during the change I would need to wait for XUD related changes in order to check the new protocol.
As such I suggest to leave the executeSwap as is for now and remove it once we implement the next version of the swap Protocol. (https://hackmd.io/s/SJ2qZUzdX)

@Daniel, I suggest we accept the PR or close it. This issue can also be assigned to a later milestone so we will not forget it.

**Comment by sangaman** [comment]
@offerm What about removing `executeSwap` from master and leaving it in a branch if you need it for testing purposes?

**Comment by kilrau** [comment]
Leaving it in a `swap_v2` branch sounds like a good idea to me

**Comment by offerm** [comment]
@sangaman I'm OK with removing it from master together with related code.

No need to keep it as a branch. I will pull it from history if needed.

go for it.

Offer

**Comment by offerm** [comment]
PR #465 

@sangaman  please review/accept
