### ISSUE TITLE
[Concept] Multiple lnd's for each user of XChange behing xud

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#418]
Switch lnds for each trade to be directly between user and user. Problem: conflicts with current plan to advertise lnd keys on `xud` hand-shake and *don't* exchange for each trade.

so instead of of the HTLCs being consructed as
`alice(aliceLND) <==> xud1LND <===> xud2LND <==> bob(bobLND) `
it would be
`alice(aliceLND) <==> whatever route <==> bob(bobLND)`

@michael1011 Please check if I got that right. If yes, I don't really see much reason why we would need this. Reason: xud will become a submarine swap / atomic swap hop and the whole HTLC route will be trustless anyways. Please think a bit more and let's discuss in this issue.

**Comment by sangaman** [comment]
I'm a bit confused, we want to run an instance of lnd for *each user*? I think that would be totally unscalable, and I don't see why it's necessary. If the intention is that user's control their own keys and funds, then I don't think there is really a role for the exchange to play and at that point they should just be running their own xud instance.

**Comment by michael1011** [comment]
@sangaman The plan for XChange is to let the users have control over their keys and funds by letting them use their own on-chain and off-chain wallets. This should be possible with (reverse) Submarine swaps. XChange would run just one LND for each chain.

@kilrau Yeah you got that right. The more I think about it the worse the idea of using the LND of the user gets. Not just because of incompatibilities between different Lightning implementations but also because of the added complexity to send the preimage to the XChange if `whatever route` doesn't include the LND of the XChange.

**Comment by kilrau** [comment]
ok, I'll leave it open for a bit, closing is your call

**Comment by kilrau** [comment]
@michael1011
