### ISSUE TITLE
Enable SIMNET

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#433]
"Simnet is a development/test network run locally that allows us to generate blocks at will, so we can avoid the time-consuming process of waiting for blocks to arrive for any on-chain functionality."

This task is about
* researching and testing SIMNET on litecoin lightning
* write instructions how to use it as an alternative to testnet

**Comment by kilrau** [comment]
Check github.com/ sparkswap/ broker/

**Comment by offerm** [comment]
The PR is very simple. I have it ready.

See LND issue #1830

**Comment by kilrau** [comment]
Sweet, please submit the PR, once it's merged and working we can close this 😎

**Comment by offerm** [comment]
Opened PR #1865 (LND). https://github.com/lightningnetwork/lnd/pull/1865

Let's see how easy it would be to get it merged.

@kilrau How would you like me to progress with this?

We can wait to see if they accept it to LND (may take time since they classified as P4. I have good relations now with Conner and Johan so this may help).

Alternatively, we cherry pick this commit to the resolver branch, but this will make the resolver branch "dirty" and harder to review. 

Can also create another branch "resolver-litecoin-simnet" that we can use.

Need to decide as this is blocking the second task:

> write instructions how to use it as an alternative to testnet

**Comment by kilrau** [comment]
I will play around with docker later, seems simnet on litecoin is working there already. If that's the case we can wait for the merge into lnd master.

**Comment by kilrau** [comment]
@offerm which route you wanna go? Conner's suggestion to fix ltcd as well?

**Comment by sangaman** [comment]
Moving this to alpha.2 because it won't be ready for the alpha.1 tag. Still a top priority though I'd say, just not a simple one by any means.

**Comment by offerm** [comment]
@sangaman what is missing on this? the test servers are using simnet and we can do too.

**Comment by sangaman** [comment]
Let's discuss on the call.
