### ISSUE TITLE
Make P2P functionality configurable

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#434]
As per consensus between @offerm @sangaman @michael1011 make this the default behavior:
* Don't initialize seed nodes db.init (enabled separately via `p2p.initializeSeeds` CLI & rpc call)
* Don't auto-detect own IP (enabled separately via `p2p.detectMyIP` CLI & rpc call)
* Don't advertise own listening address (enabled separately via `p2p.advertise` CLI & rpc call)
* Don't call `GET_NODES` (enabled separately via `p2p.discover` CLI & rpc call)

NOTE: still auto-connects to all in `nodes` table

`xud.conf`:
```
[P2P Auto-Pilot (EXPERIMENTAL)]
p2p.auto = true
```

or via CLI arg `p2p.auto` behavior reverts to:
* Initialize seed nodes via db.init (`p2p.initializeSeeds`)
* Auto-detect own IP (`p2p.detectMyIP`)
* Advertise own listening address (`p2p.advertise`)
* Call `GET_NODES` (`p2p.discover`)

**Comment by moshababo** [comment]
1) We already have a `p2p` config clause, so we can have it as `discovery` below it (`p2p.discovery`, or rather `p2p.discover`). But I don't think it represent well all this behavior. 
It's suitable only for the 3rd behavior (don't call `GET_NODES`). 
For the 2nd (don't advertise own addresses), the user actually controls the addresses, but we auto-detect his external IP and add it for him. The user can always keep his addresses list empty, and we should add a config field to enable the adding the external IP to the list. 
For the 1st (don't init seed nodes) - we already have `initDb`, which applies on all values. We can have this one as `p2p.initSeedNodes`, and make sure it would work also if the the database already exist.

2) Not advertising listening address will result in connected peer not being able to create a future outbound connection to us. Is that the goal?

3) If flag is disabled (default), you said `Don't advertise own listening address`. if enabled, you wrote the same thing. Is that a mistake?

**Comment by offerm** [comment]
@moshababo agree to most of your comments.

1. p2p.discover  can controle `GET_NODES` if false, the node will not learn about additional peers and will not try to connect them.
2. Need to add another option to control auto detect of external IP. Should be `false` by default. This will cases the address list to be empty hence no advertise)
3. by default, initDB should not add the seed nodes to the database. Note that `p2p.discover = false` reduce the need for this cases (but still I think  that it should be done). 

Still, some functionality is missing:
Assume A (default setup) connected to B using IP:PORT.
1. Upon restart of A the connection from A to B should reestablish itself using the IP and PORT used for the initial connection (regardless of what B advertised). B should not try to connect to A (which advertised no address).
2. Attempt to connect/reconnect after 5,10,15...5min after restart or disconnect. This should ensure that if both nodes restart and B starts after A the connection will be established.
3. if C connects to B, B should not tell C anything about A (since A didn't advertise) so C should not try to connect to B.
4. If C connects to A, A may only share with C the IP:PORT used by A to connect B providing that this IP:PORT is part of the information advertised by B (so we only gossip confirmed information).

I stonglt suggest to add `p2p.gossip` which control the "NODES" packet. If this is false the node should provide an empty NODES packet as a response to `GET_NODES` request. Default of `p2p.gossip` should be `false`

**Comment by moshababo** [comment]
> 1. Upon restart of A the connection from A to B should reestablish itself using the IP and PORT used for the initial connection (regardless of what B advertised). B should not try to connect to A (which advertised no address).

So you're suggesting to ignore advertised addresses from outbound connections? If so, then what's the point of advertising addresses to inbound connections?

> 2. Attempt to connect/reconnect after 5,10,15...5min after restart or disconnect. This should ensure that if both nodes restart and B starts after A the connection will be established.

We have the connection retries PR open (#392), which should handle that. Are you suggesting also to reconnect from side A after side B closed the socket? I was thinking of implementing that, but I wasn't sure it makes sense. 

> 3. if C connects to B, B should not tell C anything about A (since A didn't advertise) so C should not try to connect to B.

I assume you meant "so C should not try to connect to **A**". I think that's already the situation. If A didn't advertise addresses, B will not pass his information, because he doesn't even have his listening port. 

> p2p.gossip may have 3 levels

Are you sure we want to define level 2 (Verified) and 3 (Full) on the response side, instead on the request side?

**Comment by offerm** [comment]
IMHO:

> So you're suggesting to ignore advertised addresses from outbound connections? If so, then what's the point of advertising addresses to inbound connections?


Advertised addresses should be used if p2p.gossip is ON (verified or Full). It can also be used if the p2p.discovery is on (so you keep the information and use it next time when there is a disconnection).

>We have the connection retries PR open (#392), which should handle that. Are you suggesting also to reconnect from side A after side B closed the socket? I was thinking of implementing that, but I wasn't sure it makes sense.

I would say yes. If B shuts down it should close the socket first and A should try to reconnect to it. 
Only exception might be on protocol violation. I wouldn't do that now but maybe in the future.

>I assume you meant "so C should not try to connect to A". I think that's already the situation. If A didn't advertise addresses, B will not pass his information, because he doesn't even have his listening port.

This is not the case today since there is always advertise address due to the auto detect. Note that if A connects to B and B has no advertise data, A should not tell its peer about B address (while he know it).


>Are you sure we want to define level 2 (Verified) and 3 (Full) on the response side, instead on the request side?

This is a config setting which tells the node what to do when it is asked to gossip. If none - the node will provide anything. If verified - it will provide only verified (connected) addresses, etc.

`p2p.gossip` - what the node shoulld gossip about its peers 
`p2p.discover` - what the node should learn from its peers

if `p2p.discover` is `off`, the node will ignore the information comming from its peers and will not add new peers. 

We can also add the "verified" status to the NODES packate  and `allow p2p.discover` to have 3 levels like `p2p.gossip`. This way, if A is `p2p.gossip=Full` and B =`p2p.discover=Verified`, B will send for A only its verified peers while the NODES list from A may include also unverified addresses.

The initial setup of the node should be:

```
p2p.discover = None
p2p.gossip = Non
p2p.autodetectAddress = false

```
When such node (A) connects to B, it will ignore the NODES information from B, provides no NODES data to B and provide no address to B. If C connect to A, A will not learn from C and will not provide anything to C but still C can connect to A and should restore this connection upon restart. If D connects to C, C should not share A's contact data. 

Another example: consider `test1` `test2` `test3` all having `p2p.discover=Full`, `p2p.gossip=Full` and `p2p.autodetectAddress = false` (full mesh). If A above connects to `test1` it will still think that it is only A and test1 in the world.

**Comment by sangaman** [comment]
I like `p2p.discover` to control automatic `GET_NODES` requests.

We put in external ip discovery to be true by default deliberately as a convenience, I don't think we should be reverting that. I think our defaults should be geared towards actual users with the aim of a fully connected network, not for our development efforts where it's desirable to only have 1 or 2 peers at a time. I also think therefore that peer discovery should be on by default. In looking at the code though now, it looks like we don't even have a way to turn off automatic ip discovery without turning listening off altogether tho (I thought explicitly setting `p2p.addresses` to an empty array would do that, but evidently not), so that should change.

I don't think we need `p2p.gossip` - at least I don't see why we would care to not share requested nodes information with peers. If they want to learn about nodes, why not tell them?

I agree with not sharing any node connection info that isn't advertised, that's consistent with the current behavior.

I'd be ok with splitting up `db.init` into an option to add seed nodes and an option to add some currencies and pairs - but I'm also ok with how it is currently. Particularly with the new add pair & add currency rpc calls, it will be more convenient to use xud with `db.init` turned off.

I think bigger picture down the road - particularly if we're staking as an anti-spam technique - we could ask for nodes with a minimum stake amount or perhaps a minimum positive score indicating a successful history of executing swaps.

**Comment by kilrau** [comment]
Fixed as per your suggestions @moshababo @offerm @sangaman . Reminder: this issue exists to switch off *all* `p2p.auto` behavior *on default*. This is *temporary*, until we we feel comfortable to make it default again. This is less for our own development purposes, but mainly for our first test-exchanges to be 'in full control' and not be scared by unexpected p2p behavior which we currently definitely have. Also, to make this understandable I'm pretty convinced it should be all on or all off, that's why I renamed it to P2P Auto-pilot. Added fine-grained rpc calls as requirement, mainly for testing purposes.


Some detailed feedback:
> 1) We already have a `p2p` config clause, so we can have it as `discovery` below it (`p2p.discovery`, or rather `p2p.discover`). But I don't think it represent well all this behavior. 
> It's suitable only for the 3rd behavior (don't call `GET_NODES`). 
> For the 2nd (don't advertise own addresses), the user actually controls the addresses, but we auto-detect his external IP and add it for him. The user can always keep his addresses list empty, and we should add a config field to enable the adding the external IP to the list. 
> For the 1st (don't init seed nodes) - we already have `initDb`, which applies on all values. We can have this one as `p2p.initSeedNodes`, and make sure it would work also if the the database already exist.

`p2p.disovery indeed only represents the last bullet point. I think having all of them combined meets most use cases (either all p2p stuff is automatic or all manual), renamed to `p2p.auto` @moshababo and also all separate rpc calls to meet feedback from @offerm & @sangaman

> 2) Not advertising listening address will result in connected peer not being able to create a future outbound connection to us. Is that the goal?

Currently this is correct, but will be fixed by https://github.com/ExchangeUnion/xud/issues/365

> 3) If flag is disabled (default), you said `Don't advertise own listening address`. if enabled, you wrote the same thing. Is that a mistake?

Good catch, fixed. @moshababo 

@offerm : 

> Upon restart of A the connection from A to B should reestablish itself using the IP and PORT used for the initial connection (regardless of what B advertised). B should not try to connect to A (which advertised no address).

Clarified above that node still auto-connects to everything in `nodes` on startup. https://github.com/ExchangeUnion/xud/issues/365 will take care that a successful outbound connection ends up in nodes, no matter what the node advertises. This achieves your described behavior.

> Note that p2p.discover = false reduce the need for this cases (but still I think that it should be done).

Not really, there are other use cases for initializing seed nodes, like test-trades. 

> I stonglt suggest to add `p2p.gossip` which control the "NODES" packet.
> p2p.gossip may have 3 levels:

I think this mixes push & pull. We are currently going with a pull approach `GET_NODES` and should stick with it. If I don't call `GET_NODES`, I don't get any nodes and don't try to connect to it. I don't see what sense an empty `NODES` packet would make here.

> We have the connection retries PR open (#392), which should handle that. Are you suggesting also to reconnect from side A after side B closed the socket? I was thinking of implementing that, but I wasn't sure it makes sense.
> I would say yes. If B shuts down it should close the socket first and A should try to reconnect to it.
> Only exception might be on protocol violation. I wouldn't do that now but maybe in the future.

Not sure about this one yet, I'd not do it for now since there are definitely spamming concerns with non or wrong advertised listening addresses.

> I assume you meant "so C should not try to connect to A". I think that's already the situation. If A didn't advertise addresses, B will not pass his information, because he doesn't even have his listening port.
> This is not the case today since there is always advertise address due to the auto detect. Note that if A connects to B and B has no advertise data, A should not tell its peer about B address (while he know it).
>I agree with not sharing any node connection info that isn't advertised, that's consistent with the current behavior.

Yep, important, already logged in https://github.com/ExchangeUnion/xud/issues/365#issuecomment-416328528

> I'd be ok with splitting up db.init into an option to add seed nodes and an option to add some currencies and pairs - but I'm also ok with how it is currently. 

I think it's ok to leave db.init how it is for now.

> I think bigger picture down the road - particularly if we're staking as an anti-spam technique - we could ask for nodes with a minimum stake amount or perhaps a minimum positive score indicating a successful history of executing swaps.

:thumbsup:

**Comment by kilrau** [comment]
We just discussed with @michael1011 @sangaman to NOT do this and rather focus on fixing open P2P issue. @moshababo

**Comment by sangaman** [comment]
I do think it might be worthwhile to have a `p2p.discover` option, as well as a way to turn off automatically discovering and sharing your external ip address if none is specified. Could be separate issues or could reopen this one with a narrower scope.

**Comment by sangaman** [comment]
Reopening this to implement `p2p.discover` config option to disable sending `GET_NODES` packets automatically to discover new nodes, also to add `p2p.detectExternalIp` to optionally turn off discovering and sharing our external ip address on startup.

**Comment by rsercano** [comment]
From @sangaman; 

> we closed this issue but i think there are a few things that are still worth taking away from it. namely having p2p.discover config option. defaults to false - if false then we don't automatically send GET_NODES packets when connecting to a peer
> and also p2p.detectExternalIp, defaults to true, if false then we don't detect our external ip address in the Pool.init() method
> seems like it'd be good for you since you've been working on related parts of the code recently
