### ISSUE TITLE
[Concept] XUD GUI project

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#471]
Outsourced:
- fundrequest?
- gitcoin?
- dedicated external dev for initial effort?

**Comment by rsercano** [comment]
I'm not a designer but, with a ready-to-use theme I could get into this

**Comment by sangaman** [comment]
I haven't given much thought to theme or design, but I think the UI could have a minimalistic/clean UI  without bells and whistles since it would be targeted at administrators and power users - not mass market. Which admin themes are you referring to?

**Comment by kilrau** [comment]
Thanks for all the comments, didn't expect this 👍 We'll outsource this, it's perfect for an external frontend engineer and designer. Issue is for me to track, I got this.

**Comment by ImmanuelSegol** [comment]
Hi,
I don't know if it's relevant but you guys could perhaps do something similar to [universal app](https://github.com/spacemeshos/app). I have lots of experience with React and would love to help  :)

**Comment by sangaman** [comment]
@ImmanuelSegol That looks pretty cool. I don't expect that mobile support would be a priority fwiw, but it certainly wouldn't hurt and that looks like a good starting point.

**Comment by kilrau** [comment]
As discussed, a GUI might not be the right for our target group of technical traders, hence check https://www.npmjs.com/package/ccxt compatibility (check how sparkswap did it)

**Comment by dopetard** [comment]
As discussed, The reason I feel GUI might not be best option at this stage of the project is because the traders using XUD would need to have some level of technical proficiency (at-least with terminal) to be able to setup LND and XUD anyway.  Sparkswap is using cctx (the pakage @kilrau mentioned). Their CLI is meant as a proof of concept and its not a legit trading interface. They have mentioned that their early target users are big traders and they typically integrate into their own trading infrastructure using APIs and don't trade on the websites. [Here](https://sparkswap.com/docs/integration/ccxt) is CCTX integration part of their documentation. They are supporting the following CCTX methods: `fetchBalance`, `fetchMarkets`, `fetchOrder`, `fetchOrderBook`, `fetchOrders`, `fetchTicker` and `fetchTrades` [Here](https://github.com/ccxt/ccxt/wiki/Manual#unified-api) is the full manual of all supported CCTX methods.

**Comment by kilrau** [comment]
Thx, opened https://github.com/ExchangeUnion/xud/issues/707 closing here.
