### ISSUE TITLE
Order removed twice on match

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#478]
Right now, when we match an order as the taker, we wind up trying to remove the order twice. Once on match locally, and then once again when the maker broadcasts an order invalidation packet. We should still remove orders on local match, but we need to either not send the order invalidation packet to the taker or have the taker handle it gracefully without logging an error message.

**Comment by offerm** [comment]
Agree
```
9/14/2018, 2:35:37 PM [SWAPS] info: ResolveHash starting with hash: 9d7778979c48d0d57f62efa6c98df1d4065e481d1ee84137015e163373674b18
9/14/2018, 2:35:37 PM [SWAPS] debug: Executing taker code
9/14/2018, 2:35:37 PM [SWAPS] debug: Amount received for preImage b5aad427d945dfba4f0f4bb0e4f002cf7981a82fb6018124168372401bdfd9b9
9/14/2018, 2:35:37 PM [P2P] verbose: canceled order from 0235584e2ac9a34a13ce6f6dc9fb8aa1e7918d7701f0b4b69dc002887e6b3fbba3: {"orderId":"4adf4b31-b812-11e8-943e-2fe2d882e096","pairId":"LTC/BTC"}
9/14/2018, 2:35:37 PM [ORDERBOOK] warn: incoming order invalidation: invalid orderId (4adf4b31-b812-11e8-943e-2fe2d882e096)
9/14/2018, 2:35:37 PM [SWAPS] debug: Swap completed. preimage = b5aad427d945dfba4f0f4bb0e4f002cf7981a82fb6018124168372401bdfd9b9
9/14/2018, 2:35:37 PM [SWAPS] debug: Sending swap complete to peer: {"r_hash":"9d7778979c48d0d57f62efa6c98df1d4065e481d1ee84137015e163373674b18"}
```

Disagree with the warning message
>9/14/2018, 2:35:37 PM [ORDERBOOK] warn: incoming order invalidation: invalid orderId (4adf4b31-b812-11e8-943e-2fe2d882e096)

This should be handled (so info/debug message should appear) or be an error.

**Comment by sangaman** [comment]
It is handled, but it is unexpected, from what I understand that's exactly what warn messages are for.

**Comment by offerm** [comment]
How can you handle something which is unexpected :-)

To me `warning` is something that should be checked. If we know that this is part of our `execution` we should handle it (maybe ignore it or avoid double invalidation) and avoid the `warn`message.
If this is truly unexpected it should be an `error` (or even panic in such early stage of the project).

**Comment by moshababo** [comment]
It's `warning` because right now our protocol doesn't recognize the scenario which @sangaman specified. I agree that after fixing this, we shouldn't see this warning. 
Otherwise (in a different scenario), I don't think it's `error`. It's a result of a remote peer behavior, so it's expected. It's maybe `error` for the remote peer, not for the local node. 
The only way to handle this is to penalize the peer. You're right that this doesn't require anything by the user, so `warning` might be too much.

**Comment by moshababo** [comment]
It's `warning` because right now our protocol doesn't recognize the scenario which @sangaman specified. I agree that after fixing this, we shouldn't see `warning`. 
Otherwise (in a different scenario), I don't think it's `error`. It's a result of a remote peer behavior, so it's expected. It's maybe `error` for the remote peer, not for the local node. 
The only way to handle this is to penalize the peer. You're right that this doesn't require anything by the user, so `warning` might be too much. 

I think that handling the invalid orderId scenario gracefully is not so simple - we'll need to differentiate between a legit case and an unlegit, and that would require a lookup in the swap history. So I'd say to put the responsibility on the maker, to refrain from sending the invalidation to the taker. we'll just need to add the peer pubKey (which is already available in `handleSwapRequest`) to the deal object, to be used in `swap.paid` event handling in `OrderBook`.
