### ISSUE TITLE
[Concept] xud to verify maker order availability

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#587]
When receiving a swap request, we need to verify that the maker ownOrder is still available. Latency delays between the exchange and xud might cause some stale orders from the exchange perspective to appear as active on xud, and so to trigger an undesirable swap execution.

To avoid this, we can make xud wait for the exchange approval before accepting swap requests.
I see this more necessary for the `nomatching` mode (#145), because in this mode the exchange should be the single source of truth, while in practice, even if we'll instruct exchanges to immediately invoke order removal on xud (before doing so on their native platform), the fact that maker orders availability checks are being done on xud means that in practice xud is the source of truth.

**Comment by sangaman** [comment]
Thanks. My feeling is that we should hold off on this feature for the following reasons:

1) It introduces a good deal of complexity, the exchange/client will need to create and maintain their own service that xud can query. This service will also need perfect up-to-date information on the status of all orders, which would be complicated in a multi-threaded environment.

2) If an exchange really wants to ensure that an order can't be swapped after it is canceled/filled, they can remove it from `xud` before they cancel it internally. I'm not sure whether that makes `xud` the source of truth, but it still leaves all the matching logic in the hands of the exchange.

Basically I would not worry about this unless or until exchanges ask for a feature like this.

In thinking about this, I'm wondering if a greater concern might be how we deal with putting orders on hold during swap execution when we're in `nomatching` mode. It seems like it would be a more common situation to have an order that's been accepted for a swap but not yet swapped (a delay that can take a couple seconds or more) within `xud` that gets simultaneously filled or canceled on the exchange. We might need another subscription call to notify the client of holds being placed on orders, but it might not even be that simple since an exchange might not have any framework for putting orders "on hold" internally.

**Comment by kilrau** [comment]
Unfortunately it's indeed a fact that exchanges currently don't have a "locking" mechanism for orders.

Let's assume we are in a scenario where an exchange integrated `xud` and has one `ownOrder` which was propagated to xud and the XU network.

Method a)
1. Swap request from XU network peer comes in
2. `xud` asks exchange to lock the order
2. Swap happens (preimage released by peer)
3. `xud` updates exchange about success/failure and thus remove/unlock
Bad: the exchange had to implement the locking feature.

Method b)
1. Swap request from XU network peer comes in, preimage and hash created by maker (own xud)
2. In last step of swap procedure, before releasing the preimage, `xud` checks availability of order with exchange and if available asks to mark it filled
3. If successful: release preimage, if not: cancel swap
Bad: In https://github.com/ExchangeUnion/xud/issues/277 we decided to go for the taker releasing the pre-image to safe some ping pongs..

Please help me think this through @moshababo @sangaman @offerm @michael1011

**Comment by sangaman** [comment]
With method b) my concern is that we shouldn't back out from swaps after they've been accepted. On the other hand, I believe the swap would be almost certain to succeed by the time we're asked to release the preimage because the HTLCs are already in place.

Either way, I still am reluctant about any mechanism that confirms with the exchange before accepting or executing a swap.

**Comment by kilrau** [comment]
> On the other hand, I believe the swap would be almost certain to succeed by the time we're asked to release the preimage because the HTLCs are already in place.

That's precisely why I suggested to remove the order from the exchange's order book exactly before releasing the preimage. It's the only moment we can be 99.99% sure that the swap will succeed. Only a network or other random error can be in the way.

> Either way, I still am reluctant about any mechanism that confirms with the exchange before accepting or executing a swap.

Well I think we all agree that these situations will happen. Swaps succeed whereas the corresponding orders already got filled or cancelled internally. It will screw up the exchange's accounting and thus is a big problem. So how are you suggesting to deal with it? @sangaman 

@offerm @michael1011 your opinions?

**Comment by offerm** [comment]
The situation is also complicated for the Taker, not just for the Maker. When the taker start the swap it must block the same order from being executed on the exchange. 

This discussion is one of the reasons why I think that an exchange will not echo all its orders to XUD. It is way too complicated for the exchange to manage. Instead, IMHO, I think that the exchange will issue buy/sell order for orders which are deep in the order book and once succeed will wipe the order book against these trades.
IMHO, when we are in matching mode, the responsibility of the exchange is to place an order but also to cancel it when needed. The exchange should be ready for a response to `cancel` that this order can't be cancelled since it is `in execution`

I agree with @sangaman that 
>Basically I would not worry about this unless or until exchanges ask for a feature like this.

**Comment by moshababo** [comment]
@kilrau it seems like the discussions you started on Slack was a continuance to this. Should I close this?

**Comment by kilrau** [comment]
Let's leave it open for now

**Comment by kilrau** [comment]
We'll move our discussion here to keep it transparent. Current status of proposals:

**Comment by kilrau** [comment]
New approach makes this obsolete. Closing.
