### ISSUE TITLE
XUD does not connect to previously connected peers

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#606]
This was working in the past.

To reproduce:
- start a fresh XUD
- make sure it connected to test1,test2, test3 servers
- stop XUD
- restart XUD

it will not reconnect with these servers

Log has this:
```
10/26/2018, 7:52:37 PM [P2P] info: Connecting to known / previously connected peers
10/26/2018, 7:52:37 PM [RPC] info: gRPC server listening on localhost:8886
10/26/2018, 7:52:37 PM [P2P] info: Completed start-up connections to known peers.
```

**Comment by sangaman** [comment]
I was able to reproduce and fix. It looks like an old bug actually, my best guess is that the test nodes were previously advertising listening addresses but are not currently. It should not matter, since we should be trying to reconnect to them with the last successful address which was not happening before the fix.

**Comment by kilrau** [comment]
How exactly did you fix this? @sangaman

**Comment by sangaman** [comment]
I added a check to see if a node has a valid `lastAddress` when looking to connect to it, which can take the place of a listening address. You can see the details in the PR.
