### ISSUE TITLE
Swaps security issue: currency/amount info

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud#615]
In `OrderBook.handleSwapRequest`, the maker verifies his order availability, and accepts the deal. Further validation is applied on LND requests (`validateRequests`), based on the deal info. But the deal info was never validated on the maker side. It means that the maker is blindly accepting the taker currency/amount calculation in regards to the deal.

**Comment by sangaman** [comment]
I'll have a PR ready for this tomorrow.

**Comment by sangaman** [comment]
FWIW I don't think this is a bug per se, more like functionality that is lacking. I brought this concern up in #359 , but we went with this oversimplified approach deliberately to get the basic functionality working sooner. Still, I'm thinking I should have created an issue for this right away so that we wouldn't lose track of it, it's certainly critical functionality.
