### ISSUE TITLE
Improved buy/sell output for xucli

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#620]
As per https://github.com/ExchangeUnion/xud/issues/612#issuecomment-434207811 we aim for the following output format:

```
xucli buy 0.0005 LTC/BTC market --stream

market order accepted
matched with peer order : .......
attempting swap: .....
swap failed: .....
peer order removed from book: .....
attempting swap with: .....
swap failed: .....
peer order removed from book: .....
attempting swap with: .....
swap failed: .....
no more matches found
quitting.
```

Successful case:
```
xucli buy 0.0005 LTC/BTC market --stream

market order accepted
matched with peer order : .......
attempting swap: .....
swap succeeded: .....
done.
```

**Comment by sangaman** [comment]
This is an extension of #558, and a prerequisite is #609. I'll work on these since it seems like it'd be fairly helpful for our testing and simnet setup.

**Comment by kilrau** [comment]
1. CLI will use output from grpc stream
2. placeOrder (buy/sell) SYNC: keep current events, add swap failure event -> @sangaman make sure only meaningful (results) events are in the SYNC response

**Comment by sangaman** [comment]
Per our discussion on the weekly call I'm thinking of leaving out the "attempting swap" event because it does not exist on our grpc call. Maybe that could be for a future enhancement although I don't think it's really necessary as it has little to no value for anything but the cli, and even for the cli it is just cosmetic.
