### ISSUE TITLE
Held amount not released if taker doesn't follow the swap protocol 

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#653]
One a swap agreed between the taker and the maker, the maker is holding the agreed amount for the swap.

In case of a swap error, the amount is being release #637 and available for trading.

However, if the taker is not starting the swap and is not sending a swap error  the amount will be kept on hold by the maker until a restart of the maker.

**Comment by sangaman** [comment]
I figure the best solution would be to set a timeout on swaps that are accepted but never executed, right? At that point we'd fail the swap and reuse the existing logic to release the hold.

**Comment by kilrau** [comment]
Agree, timeouts are the thing to do (Sidenote: Also will do away with the punishing idea in favor of timeouts, more in an upcoming tech paper PR).

More thoughts on timeouts:
* Let's assume we have trade timeout from accepting a dealRequest to preimage release of 10s
* Collaboratively cancelling a trade (after reaching timeout) can be done any time during the trade. Even when HTLC route is completely setup. I understand we currently take care of holds/release holds of orders amounts within `xud`. **Question**: Do we already take care of amounts locked in HTLCs in the channels when a swap fails? If not, I propose to open a separate issue which takes care of collaboratively cancelling a swap so that both sides get their funds back from the HTLCs immediately, assuming both parties are responsive and cooperate. This includes both parties agree on a timeout when accepting a dealRequest. Use Case: I want to cancel a trade because it a) reached the timeout or b) any other reason. @offerm @sangaman 
* Unilaterally cancelling a trade (after reaching timeout or any other reason) is the tough part from swap/HTLC perspective since here the assumption is that the other party is not responsive/doesn't cooperate. Currently this would require closing a channel and a lengthy `cltv` waiting time which is measured in blocks. I also propose to open a separate issue here and continue discussing there and exchange ideas. @offerm @sangaman 

In short: we

**Comment by kilrau** [comment]
What do you guys think? Something for you? @erkarl 

First steps leaving the happy swap flow :)
