### ISSUE TITLE
[Concept] Enforce short Timeouts for HTLCs (Free Options Problem)

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#660]
This issue is to track discussion around the concept on how to thoroughly enforce short timeouts (seconds, not minutes or hours) and to hold & release amounts in the HTLCs with these. In payment channels.

Let's assume we have trade timeout from accepting a dealRequest to preimage release of 10s. We need to solve:
* https://github.com/ExchangeUnion/xud/issues/653: Collaboratively or  unilaterally cancel the trade and release order amounts in `xud` after timeout
* This issue: **Collaboratively** cancelling a trade (after reaching timeout) can be done any time during the trade. Even when HTLC route is completely setup. We currently are discussing take care of holds/release holds of orders amounts within `xud`. **Question**: Do we already take care of amounts locked in HTLCs in the channels when a swap fails? If not, I propose to open a separate issue which takes care of collaboratively cancelling a swap so that both sides get their funds back from the HTLCs immediately, assuming both parties are responsive and cooperate. This includes both parties agree on a timeout when accepting a dealRequest. Use Case: I want to cancel a trade because it a) reached the timeout or b) any other reason. 
* This issue: **Unilaterally** cancelling a trade (after reaching timeout) from swap/HTLC perspective: the assumption is that the other party is not responsive/doesn't cooperate. Currently this would require closing a channel and a lengthy `cltv` waiting time which is measured in blocks = too long.

**Comment by sangaman** [comment]
If a swap fails because the payment fails, the HTLCs should be failed with nothing locked up. HTLCs being delayed should typically mean that the recipient or a node along the route is misbehaving.

I don't see the use case to collaboratively cancel a trade - once it's accepted then we attempt the swap immediately. If the swap is delayed, it's probably because the other party is not being responsive, and so we probably won't be able to collaborate on anything.

For unilaterally canceling a trade, I don't think we need to close any channels or deal with any HTLCs. We just mark the deal as errored internally and send a swap failed packet, if we get any requests to resolve a hash for a deal that has been timed out/canceled then we just fail it and the HTLC will fail and no longer be pending. @offerm can correct me if I'm wrong but that's my understanding.

**Comment by kilrau** [comment]
> The taker can `cancel` the trade before he release the preimage.
> The maker can `cancel` the trade before he sends the second leg HTLC. Once he sends the second HTLC he is committed and can't cancel the trade (the taker may do that but the maker can't).
> Once the taker released the pre-image there is no `cancel` option.

Agreed.

> Now, the maker may hold on the taker's HTLC and the taker may hold on the maker's HTLC. On such case, the parties may close the channel to get back the locked funds. They don't have to.

They don't have to? What other options do they have?

> What is important here is that there is no incentive for the parties to hold on the HTLC.

Let me quote from CJPs paper on incentives to delay a trade if there are **no** enforced timeouts:
• After incoming X are locked in, Maker can delay locking in outgoing Y. Just
before Taker's incoming HTLC time-out is expected, Maker decides:
- The value of X has increased w.r.t. Y -> lock in the outgoing Y.
- The value of X has decreased w.r.t. Y -> cancel the transaction.

• After incoming Y are locked in, Taker can delay claiming the incoming Y.
Just before Taker's incoming HTLC time-out is expected, Taker decides:
- The value of X has increased w.r.t. Y -> cancel the transaction.
- The value of X has decreased w.r.t. Y -> claim the incoming Y.

If both attack each other they will always end up with a cancelled transaction.

> I think this discussion is important in the non-matching mode only.

Since both matching and no-matching mode have to be compatible with each other and have to have the same definition of "when is a trade committed" and how timeouts are handled I don't see why it only applies to one.

**Comment by kilrau** [comment]
Updated scope of this issue:
from when do we regard one sided "committed" to a trade" and how can we take action if one side times-out and doesn't cooperate on gracefully cancelling the trade

**Comment by offerm** [comment]
> > Now, the maker may hold on the taker's HTLC and the taker may hold on the maker's HTLC. On such case, the parties may close the channel to get back the locked funds. They don't have to.
> 
> 
> They don't have to? What other options do they have?
> 

They can leave the HTLC panding and continue using the channel. Only when the channel is running out of capacity there will be a need for closing it. HTLC may stay pending due to the peer LND disconnected. In such case, it is better to wait for the peer's LND to come back and close the HTLC and not force close the channel.

> > What is important here is that there is no incentive for the parties to hold on the HTLC.
> 
> 
> Let me quote from CJPs paper on incentives to delay a trade if there are no enforced timeouts:
> • After incoming X are locked in, Maker can delay locking in outgoing Y. Just
> before Taker's incoming HTLC time-out is expected, Maker decides:
> 
> The value of X has increased w.r.t. Y -> lock in the outgoing Y.
> The value of X has decreased w.r.t. Y -> cancel the transaction.
> • After incoming Y are locked in, Taker can delay claiming the incoming Y.
> Just before Taker's incoming HTLC time-out is expected, Taker decides:
> 
> The value of X has increased w.r.t. Y -> cancel the transaction.
> The value of X has decreased w.r.t. Y -> claim the incoming Y.
> If both attack each other they will always end up with a cancelled transaction.
> 

Once the maker accepted the swap by sending back the P2P packet, the parties are committed and the swap should happen. 
If any of the parties delay the swap or cancel the swap he should be panelized and eventually banned.
The taker may play with the HTLC once or twice but it is not a game that you want to play for the long run. also, if the taker waits with the HTLC and eventually accepts it, the maker may not release the preimage and cause the taker to close the channel. 
I can't see a real incentive for any party to do that.

> > I think this discussion is important in the non-matching mode only.
> 
> 
> Since both matching and no-matching mode have to be compatible with each other and have to have the same definition of "when is a trade committed" and how timeouts are handled I don't see why it only applies to no-matching mode only.

Let me clarify - I see no benefit for the taker and/or maker in the current swap architecture that we have that is working nicely in matching mode.
For no-matching mode we may need a different swap solution where this problem may be more relevant.
Time will tell.
