### ISSUE TITLE
Enhance log to include milliseconds 

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#686]
Enhance log output to inlcude milliseconds in each printing.

Today we only should the time up to the seconds.

**Comment by rsercano** [comment]
This issue seems pretty easy, so I can take over if you're okay with it ? For the miliseconds if we want to print miliseconds then we need to **specify format** instead of printing **current javascript runtime format**. I can take this format in config file and provide a default one if not provided.

**Comment by sangaman** [comment]
Oh yes it had just slipped my mind, go for it if you have time @rsercano. I agree it would be a nice feature.

**Comment by rsercano** [comment]
Now we pick date format from configuration, so everyone can change as how they wish, but I can set the default format as LND if you wish @offerm ?

**Comment by kilrau** [comment]
default format as LND sounds good! @rsercano
