### ISSUE TITLE
SubscribeAddedOrders response missing `side` field for buy orders

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud#725]
![image](https://user-images.githubusercontent.com/4723958/49495544-46bb4780-f89e-11e8-85cc-522217c4f5bb.png)

**Comment by kilrau** [comment]
@rsercano ?

**Comment by rsercano** [comment]
Hopefully this Saturday I'll check both issues @kilrau sorry for the delay

**Comment by rsercano** [comment]
This is strange because it seems like the side field is set everytime, even in cases that state of the order is not clear; [check here](https://github.com/ExchangeUnion/xud/blob/d5387576f5620c7bb633f04a4c6de439328678d0/lib/grpc/GrpcService.ts#L34) 

Are you sure this bug still exist with the current master ?

**Comment by sangaman** [comment]
Where is the output in the original post from? It does seem like we always set a side, for both buys and sells. I'm wondering if the issue is that since the value for `BUY` is 0, and if you do something like `if (side)` then it may treat 0 as false.

**Comment by rsercano** [comment]
Great point @sangaman will investigate a bit further

**Comment by rsercano** [comment]
No luck ! Can you please tell us how to reproduce this ? @reliveyy

**Comment by reliveyy** [comment]
@rsercano Please check [my testing code](https://github.com/reliveyy/xud-exchange-integration-example/blob/dev/xud_subscribe.py#L16) and uncomment two print lines. And this is reproduced on gcloud exchange-b.

**Comment by rsercano** [comment]
@reliveyy yeah now I reproduced it, you're right this seems a bit tricky can be related with streaming **zero** will try with another value.

**Comment by rsercano** [comment]
Hello again, seems like our streaming is working properly, somehow generated enum in python doesn't print properly so that's nothing to do with the core code.

I'm not really familiar with **python**, but if you make it write `response.side`  it prints properly `0` or `1` for the corresponding value.

I guess this issue can be closed.

**Comment by reliveyy** [comment]
Just confirmed it's my python code printing issue. @rsercano

**Comment by kilrau** [comment]
Good job catching this one! @rsercano
