### ISSUE TITLE
SubscribeAddedOrders should have `existing` true by default

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud#728]

**Comment by reliveyy** [comment]
I think let `existing` be true may cause unexpected overload on this RPC call and I think the existing orders push feature in `SubscribeAddedOrders` is little wired because there is another order feed call `SubscribeRemovedOrders`. Why not put existing orders push in this RPC call? Maybe another RPC call `GetOrders` should be in `nomaching` mode.

**Comment by kilrau** [comment]
As we discussed in https://github.com/ExchangeUnion/xud/issues/534, "existing" should be true on default @ImmanuelSegol

**Comment by kilrau** [comment]
More feedback from @reliveyy :
* he'd prefer a combined `SubscribeOrders` feed with `added` and `removed` events.
* `existing` flag easier to understand like this(rn `existing` only in `SubscribeAddedOrders`, but not in `SubscribeRemovedOrders, true on default is fine, all flag fine too
* with the `all` flag the initial push could be very large (potentially all orders within exchange union). In this case this call should handle that new `added` and `removed` orders get buffered while the initial push is still ongoing

**Comment by kilrau** [comment]
What do you think? @ImmanuelSegol @sangaman @moshababo

**Comment by ImmanuelSegol** [comment]
> More feedback from @reliveyy :
> 
> * he'd prefer a combined `SubscribeOrders` feed with `added` and `removed` events.
> * `existing` flag easier to understand like this(rn `existing` only in `SubscribeAddedOrders`, but not in `SubscribeRemovedOrders, true on default is fine, all flag fine too
> * with the `all` flag the initial push could be very large (potentially all orders within exchange union). In this case this call should handle that new `added` and `removed` orders get buffered while the initial push is still ongoing

1) What would be the benefit of having them combined?
2) I didn't really understand what you wrote there.
3) I agree this could be an issue when dealing with massive amounts of existing orders.

I think `streamorders` command is pretty awkward why do we return streamed orders with existing order? If we separate the command to `getExistingOrders` and `streamorders` it would solve most of these problems.

**Comment by kilrau** [comment]
1. Seems more logical
2. `SubscribeAddedOrders` has a `existing` flag, whereas `SubscribeRemovedOrders` doesn't. Confusing in the first moment (even though it makes sense).

I like your proposal to have `GetExistingOrders` and `StreamOrders`. It would enable to
* have a very clear distinction between existing orders and an order stream and make it more flexible for the exchange to use
* no confusion with flags
* no buffer required

I'd propose to go for it. Just asked @reliveyy , he likes it too. Other opinions? @offerm @sangaman @moshababo

**Comment by sangaman** [comment]
I'm hesitant to combine the added and removed calls - we discussed this a lot and it would be a pretty significant change. Personally it still makes more sense to me to keep them separate, and maybe a solution would be to have a separate combined call like `SubscribeOrders`. But if we want to discuss that more let's put it in a separate issue.

I see no reason to put an `existing` flag on `SubscribeRemovedOrders`. It just doesn't apply at all.

We already have a "GetExistingOrders" call - it's just `GetOrders` (or as it may soon be called `ListOrders`). We used to have a "max results" limit on there which maybe we can put back, but then we probably need to look at sorting orders as otherwise the orders returned are arbitrary.

The point of returning existing orders on the streaming call is to be able to get all orders and stay up to date with them in a single call, as well as eliminating the possibility for any missed orders between the `GetOrders` and `SubscribeAddedOrders` calls.

**Comment by ImmanuelSegol** [comment]
> As we discussed in #534, `existing` should be `true` on default. It was not. @ImmanuelSegol
> 
> As Yangyang suggested, we can add a default limit of 10 buy and 10 sell. `all` flag `false` on default. `true` returns all orders.

@kilrau When returning a limit of 10 buy/sell should we return the first in the list, or should we return buy/sell orders based on some sort of "relevance", such as date of creating etc.
As @sangaman stated in #730 Im returning an arbitrary set of orders which is not useful.

**Comment by kilrau** [comment]
> Im returning an arbitrary set of orders which is not useful.

That is true I'm afraid. We should return the 10 **best** buy/sell orders. Anyhow, after some more thinking and considering @sangaman 's response, I fix the scope of this issue to:
* don't change any naming of the calls
* add buffer for `existing` flag in `SubscribeAddedOrders` to not block order updates while `existing` is still running. It always returns **all** orders from a peer, no matter how long that may take.
* add back the `max results` limit of buy & sell orders for the `ListOrders` call. Default set to 10 in `xud.conf`. `all` will return all. Add description in `sample-xud.conf` for that. This returns the 10 *best* (closest to mid-market price) orders. So yes, we need to sort in order to do that. Since we need to sort anyways, we can conveniently return them in descending order like in an order book.

What do you think? @ImmanuelSegol @sangaman

**Comment by sangaman** [comment]
I think the max results/sorting on `getorders` should be handled separately, and let's talk about it tomorrow.

I don't think a buffer would really apply in this case. Sending all orders should happen very fast, even a large number of them. `xud` loops through everything once and then moves on, we're not blocking on or waiting for data to be transmitted. Also, we specifically want this all to happen in one go - otherwise we may miss updates to the order book. Either way, this is not a call that should be made very often, it really should only pertain to initialization.

**Comment by ImmanuelSegol** [comment]
@kilrau @sangaman I agree I think this isuue should only take care of **`existing` true by default**.
We should open up another issue about max results/sorting on getorders.

**Comment by kilrau** [comment]
Ok, then let's do this. Please go ahead and do an offshoot for the max results and sorting. @ImmanuelSegol

**Comment by sangaman** [comment]
@kilrau Did you mean an issue for max results/sorting on the `GetOrders` call? That would make more sense to me.

**Comment by kilrau** [comment]
> @kilrau Did you mean an issue for max results/sorting on the `GetOrders` call? That would make more sense to me.

Yes, fixed https://github.com/ExchangeUnion/xud/issues/748
