### ISSUE TITLE
basic webproxy tests

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#853]

**Comment by erkarl** [comment]
Did some testing on this one. Looks like the gRPC proxy server starts up nicely when `disable = false` is set in `xud.conf`. 

I wasn't, however, able to access the endpoint due to SSL issues. Should we add documentation to master branch on how to use these proxy endpoints via curl (while SSL enabled)?

**Comment by kilrau** [comment]
> Should we add documentation to master branch on how to use these proxy endpoints via curl (while SSL enabled).

Feel free, but not important. raiden should be the only client using web proxy endpoints for now and that setup has to work without config. @offerm

**Comment by kilrau** [comment]
Closed by @erkarl
