### ISSUE TITLE
Channel management

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#909]
### Motivation:
Our [new docker setup](https://github.com/ExchangeUnion/xud/issues/246) will ask for a "channel strategy" - direct or multi-hop. Due to a serious raiden routing issue (raiden uses a new secret for every new route it tries) we probably have to make direct channels the default for now and only allow multi-hop for btc and ltc.

### Specification:
This issue is about creating a new config option for the two modes. Docker setup will manipulate this config based on user input. Also there should be a place where "Open <coin> channel with <x> amount to xud <nodepubkey>. This will also be the place where the docker setup persist this user input.

**Comment by sangaman** [comment]
I don't see why we would need a config option for direct channel mode. Even given the raiden bug, if we can't swap (whether due to lack of a direct channel or for any other reason) we will fail the sanity swaps and therefore not send or accept any orders with peers for the trading pairs that can't be swapped.

**Comment by kilrau** [comment]
Ok, where else would you persist this?

**Comment by erkarl** [comment]
As discussed during the call this issue is now about:
* enabling/disabling autopilot for swap clients that have that functionality (currently only lnd) via our gRPC
* adding a gRPC call to open channels by providing `xudPubKey`, `currency` and `amount`
