### ISSUE TITLE
`xud` master password

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#912]
Needs some research if this could work like this @sangaman :

* let's btclnd create memonic, use it for xud and inject it in all other non-preexisting nodes
* encrypts xud's private key and all other nodes non-preexisting nodes private key with `xud` master password
* lnd macaroons, full-node rpc passwords
* pre-existing LND/raiden/fullnode's: user has to enter passwords and xud stores and encrypts these pws with master password. Needs great explainer on what is happening here and why this is secure.
* as just discussed, this should be a xud core function exposed as gRPC and CLI call

**Comment by kilrau** [comment]
Need your feedback on the concept in general and also if you see any reason why this shouldn't be part of xud core @sangaman @erkarl

**Comment by kilrau** [comment]
Divide & conquer for @sangaman @erkarl

**Comment by kilrau** [comment]
As per https://github.com/ExchangeUnion/xud/pull/889#issuecomment-490765364, this includes simplifying and integrating the following LND calls:
https://api.lightning.community/#genseed
https://api.lightning.community/#initwallet
https://api.lightning.community/#unlockwallet

**Comment by sangaman** [comment]
Karl is going to look into how we can generate an ethereum address based on a seed (which does not seem to be a built in feature of geth but which is done by open source projects like MetaMask and MyEtherWallet). This would require xud to communicate directly with geth most likely, *unless* Raiden exposes API calls that will do this for us (as well as allowing us to unlock encrypted ethereum keys).

The plan is still to have xud prompt for a password when it starts up and attempt to unlock every lnd wallet (and eventually raiden/geth wallet) using that password. And if xud starts up and doesn't find an xud pubkey such that it has to create a new one, it will generate a seed (using any one of the lnd instances) and attempt to init wallets for every lnd client we have configured using that seed, and also prompt for a password and set that for every newly initialized wallet. That same seed will be used to derive the xud key and same password will be used to encrypt it.

We'll need to change the flow for initializing LndClients, since we can't call GetInfo on an lnd instance that is still locked or uninitialized.

**Comment by kilrau** [comment]
https://github.com/iancoleman/bip39

**Comment by kilrau** [comment]
Closed by https://github.com/ExchangeUnion/xud/pull/1006
