### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#917]
* Channel State backups: [SCB](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md). LND fires an event whenever there is an update to the SCB file. Call: https://api.lightning.community/#subscribechannelbackups 
xud should then copy it to [location set by user](https://github.com/ExchangeUnion/xud/issues/246). Raiden: the channel state db should bin `~/.raiden` and be backed up the same way. Not sure if events are available.
* `xud.db`, `xud.conf`, `lnd.conf`, `raiden conf`, `/root/.xud/tor` (xud container)

Anything I forgot?

**Comment by michael1011** [comment]
As discussed I think that this should be not part of XUD by default. What would be best in my opinion is to put this functionality in a separate executable and folder in `lib` so that it can still reuse the config parsing and LND clients that already exist without bloating the code base too much.

Other options would be:
- part of the XUD that can be enabled with a config parameter
- in a separate repository (this just makes sense if we have other things to outsource from the main repository. Creating and maintaining a repo just for this is too much work in my opinion)

**Comment by sangaman** [comment]
You're thinking of a new script that can be run separately from xud, but still reuses some of our existing code like the LndClient? How would it be run?

**Comment by kilrau** [comment]
> separate executable and folder in `lib`

SGTM, could you quickly explain how it works and be triggered by xud before you go ahead and do it?

**Comment by michael1011** [comment]
A new file `bin/xud-backup` that can be executed if the user wants to have these backups. If not the users just ignores that file and doesn't get bothered.

**Comment by kilrau** [comment]
Moved to `1.0.0-beta`, we'll bring it as an (important) update to testnet.

**Comment by kilrau** [comment]
EDIT: added xud db
