### ISSUE TITLE
[Discussion] API in layers

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#924]
This issue is to track discussion about dividing the `xud` code base into a "core" and use-case specific functionality into separate modules.

In particular use cases are different for:
* individual traders
* exchanges

Current ideas:
* Sub-Servers (compare [lnd](https://github.com/lightningnetwork/lnd/releases/tag/v0.6-beta))
* Separate clients connecting to `xud core` via API

It would be great to get more input on this.

**Comment by ImmanuelSegol** [comment]
@kilrau  I was wondering should we perhaps think of splitting `xud` into individual components?
For example, the `logger` and `cli` I think would we a good idea.

What do you guys think?

**Comment by sangaman** [comment]
After researching the Sub-Servers approach lnd uses (and working with it for their invoicesrpc subserver), it seems more like a way of expanding/re-working their rpc API in a more modular and backwards compatible way. I don't think that's exactly what we're going for here, although we may want to do something like that down the road anyway. Right now all our calls are bundled into a single service, but we can organize them into separate areas of interest.

My concern here is two-fold:

1. Not bloating the xud codebase with code that's not relevant to its core functionality.

2. Not increasing the cpu/RAM burden of xud. Particularly cpu, since we are single-threaded and time spent doing anything cpu intensive is time spent not responding to p2p packets, lnd calls, etc...

I'll think about this some more in terms of best practices/approaches  and we can also discuss this on the next call again.

@ImmanuelSegol You mean splitting them into separate repositories and packages, right? I've thought about that as well and it might make sense. The cli in particular is pretty much separate functionally, but I'm not sure it's worth it with logger since that's pretty much just a wrapper around winston. I think it would make sense to discuss this on a call as well.

**Comment by kilrau** [comment]
Gotcha on lnd's subserver approach. Any other ideas? @erkarl @moshababo

**Comment by erkarl** [comment]
To start with it makes sense to separate the CLI to a standalone repository in order to provide an example project how to consume our API to build user interfaces.

Additionally, we could think about having a helper library that has common data formatting/processing functionality. The benefit would be that it decreases the development complexity for the UI layer and also handles data processing in a separate thread, isolated from `xud-core`.

**Comment by kilrau** [comment]
> To start with it makes sense to separate the CLI to a standalone repository in order to provide an example project how to consume our API to build user interfaces.

Sounds good, how about ideas on how to split of functionality specific to exchanges? Similar to the CLI which would communicate with `xud` core via the gRPC?
