### ISSUE TITLE
rhash vs rpreimage

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#987]
Daniel,

Need your help to understand the blow:
```
26/05/2019 19:41:15.361 [SWAPS] debug: New deal: {"takerCltvDelta":1,"rHash":"fd8d5e6c7917e17f6b4523a63f0a35ad7f45b822543fd86d7eebdbbfcf4fbcd4","orderId":"36a0c280-7fee-11e9-9d3e-99dc6
3a12b46","pairId":"WETH/BTC","proposedQuantity":10000,"rPreimage":"a8024292e007b82485f0b6783016fffae49dc8c941a7c55a611db6488f6f2a07","takerCurrency":"WETH","makerCurrency":"BTC","taker
Amount":100000000000000,"makerAmount":315,"destination":"02d693d951ce4fc116b2b5e22e8e4966dd3cf9ad7600b8de24190d6af429f260c0","peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee29
38e132b52cab0a0d9cfc6","localId":"3962c8b0-7fee-11e9-a77b-efa6070e4bb6","price":0.0315,"isBuy":false,"phase":0,"state":0,"role":0,"createTime":1558899675359}
```

The preimage is `a8024292e007b82485f0b6783016fffae49dc8c941a7c55a611db6488f6f2a07`

If I use sha256 (https://emn178.github.io/online-tools/sha256.html) on this string I get:
`319050e7e40697f451d4386c6ccc361b6e10c0817f9d6e369fa00f1d9f25ea02`

Which is different from the `rhash` listed above.  What am I missing?

Here is a secret and a secrethash that is working well for raiden:
secret:  0x2ff886d47b156de00d4cad5d8c332706692b5b572adfe35e6d2f65e92906806e
secrethash : 0x1c8f640789059e0d200dc69cca1967dc0498760374de99a24eb7221c9a5edb6e

Looking forward for your ideas.

**Comment by offerm** [comment]
FWIW - This produces a correct hash:
```
  const rPreimage = '2ff886d47b156de00d4cad5d8c332706692b5b572adfe35e6d2f65e92906806e';
  const rHash = createHash('sha256').update(rPreimage).digest().toString('hex');
```

**Comment by sangaman** [comment]
@offerm This stumped me for a bit too, but the issue here is that the online tool you linked to is hashing the string `a8024292e007b82485f0b6783016fffae49dc8c941a7c55a611db6488f6f2a07`, presumably as utf8. But we are trying to hash the raw data without concern for the encoding, so we first convert the hex string to bytes, then hash the bytes. I believe this is what lnd does as well.

You can verify this here with a tool which will hash hex strings: http://extranet.cryptomathic.com/hashcalc/index

Let me know if we can close this issue.

**Comment by offerm** [comment]
It cant be closed as we need a solution for raiden. We need to support two
encodings or find a way to convert one to the other that can be done in the
resolver

**Comment by sangaman** [comment]
The plan is to address this on the Raiden side now, this issue will be closed once that is completed but it's outside of xud.

**Comment by offerm** [comment]
Implemented on raiden via the integration code with XUD.
